CREATE TABLE `account` (
  `id` int(11) NOT NULL,
  `type` varchar(20) DEFAULT NULL,
  `firstname` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `lastname` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `address` varchar(400) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `city` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `sector` varchar(500) DEFAULT NULL,
  `country_id` int(11) DEFAULT NULL,
  `states` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `telephone` varchar(15) DEFAULT NULL,
  `mobile` varchar(15) DEFAULT NULL,
  `lang` varchar(10) DEFAULT NULL,
  `cardholder` varchar(100) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `birthday` datetime DEFAULT NULL,
  `state` tinyint(4) DEFAULT '1',
  `username` varchar(100) DEFAULT NULL,
  `password` varchar(1000) DEFAULT NULL,
  `referral_id` int(11) DEFAULT NULL,
  `gender` varchar(11) DEFAULT NULL,
  `cgroup_id` int(11) DEFAULT NULL,
  `params` text,
  `company` varchar(400) DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `about` text,
  `verifymobile` int(11) DEFAULT NULL,
  `phonecode` varchar(10) DEFAULT NULL,
  `activation` varchar(10) DEFAULT NULL,
  `ratings` varchar(20) DEFAULT NULL,
  `coverphoto` varchar(200) DEFAULT NULL,
  `cards` text,
  `bank_code` varchar(100) DEFAULT NULL,
  `account_no` varchar(100) DEFAULT NULL,
  `holder` varchar(100) DEFAULT NULL,
  `bank_name` varchar(100) DEFAULT NULL,
  `fbtoken` varchar(200) DEFAULT NULL,
  `logo` text,
  `image_agency` varchar(500) DEFAULT NULL,
  `color` varchar(100) DEFAULT NULL,
  `fax` varchar(100) DEFAULT NULL,
  `accept_license` tinyint(4) DEFAULT '0',
  `name_account` varchar(200) DEFAULT NULL,
  `number_agents` int(11) DEFAULT NULL,
  `reason_social` varchar(200) DEFAULT NULL,
  `postalcode` varchar(50) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `number_account_child` int(11) DEFAULT '0',
  `properties_seen` varchar(5000) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;



INSERT INTO `account` (`id`, `type`, `firstname`, `lastname`, `email`, `address`, `city`, `sector`, `country_id`, `states`, `zip`, `telephone`, `mobile`, `lang`, `cardholder`, `created`, `birthday`, `state`, `username`, `password`, `referral_id`, `gender`, `cgroup_id`, `params`, `company`, `image`, `about`, `verifymobile`, `phonecode`, `activation`, `ratings`, `coverphoto`, `cards`, `bank_code`, `account_no`, `holder`, `bank_name`, `fbtoken`, `logo`, `image_agency`, `color`, `fax`, `accept_license`, `name_account`, `number_agents`, `reason_social`, `postalcode`, `created_by`, `created_date`, `number_account_child`, `properties_seen`) VALUES
(166, 'admin', 'Super', 'Admin', 'quan@joombooking.com', 'duc yen dduwcs tho ha tinh', 'ha tinh', NULL, 0, '', '', '12', '342064718', '', NULL, NULL, '1992-10-10 00:00:00', 1, 'admin', '$2a$10$Do5S/hD6cKQwXl1u0FEpA.SmwVYU9naSvmqScncLrNF4BMzV8PQYa', NULL, NULL, NULL, '', '', '', '', 0, '', '', '', '', '', '', '', '', '', '', 'store/public/images/user/user_166/logo/1557983343131.png', NULL, '{\"r\":\"241\",\"g\":\"112\",\"b\":\"12\",\"a\":\"5\"}', '342064718', 0, NULL, 0, 'joombooking', '480000', NULL, NULL, 30, '[20,18]'),
(209, 'admin', 'Admin', 'M.', 'admin@mandexpa.lu', 'paris', 'paris', NULL, NULL, NULL, NULL, '123', '123', NULL, NULL, NULL, NULL, 1, NULL, '$2a$10$VECZeTpxl1bfq30SrOOoxuE.rRTG08bONXtexeAsbhc9cGz50Vwyu', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '{\"r\":\"241\",\"g\":\"112\",\"b\":\"12\",\"a\":\"5\"}', '0', 0, 'Admin', 0, 'Mandexpa', '123', 166, NULL, 16, '[30,3,1,9,20,26,43,42]'),

-- --------------------------------------------------------



CREATE TABLE `activity` (
  `id` int(11) NOT NULL,
  `pro_id` int(11) NOT NULL,
  `contact_id` int(4) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` int(255) DEFAULT NULL,
  `created` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------



CREATE TABLE `agenda` (
  `id` int(11) NOT NULL,
  `property_id` int(11) DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `property_created_by` int(11) DEFAULT NULL,
  `owner_property_id` int(11) DEFAULT NULL,
  `meeting_date` datetime DEFAULT NULL,
  `meeting_hour` datetime DEFAULT NULL,
  `created_at` datetime DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `subject` int(11) DEFAULT NULL,
  `path_doc` varchar(200) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO `agenda` (`id`, `property_id`, `created_by`, `property_created_by`, `owner_property_id`, `meeting_date`, `meeting_hour`, `created_at`, `status`, `subject`, `path_doc`) VALUES
(1, 12, 261, 262, NULL, '2019-06-10 17:00:00', '2019-06-03 08:30:01', '2019-06-03 09:56:14', 0, 1, NULL),
(2, 2, 261, 262, NULL, '2019-06-12 17:00:00', '2019-06-04 08:00:00', '2019-06-04 08:42:32', 1, 1, 'store/private/agenda/2/1559637849175_Bon_de_visite_2019_Mandexpa.docx'),
(3, 48, 234, 235, 235, '2019-06-14 22:00:00', '2019-06-14 12:00:00', '2019-06-14 12:20:08', 1, 1, 'store/private/agenda/3/15605148257820_Bon_de_visite_2019_Mandexpa.docx'),
(4, 48, 234, 235, 235, '2019-06-14 22:00:00', '2019-06-14 12:00:01', '2019-06-14 14:22:08', 2, 1, ''),
(5, 58, 235, 234, 250, '2019-06-18 22:00:00', '2019-06-14 14:00:01', '2019-06-14 16:30:59', 1, 1, 'store/private/agenda/5/15610423676260_Bon_de_visite_2019_Mandexpa.docx'),
(6, 67, 234, 235, 208, '2019-06-20 22:00:00', '2019-06-20 13:15:01', '2019-06-20 14:50:35', 1, 1, 'store/private/agenda/6/15629895713340_Bon_de_visite_2019_Mandexpa.docx'),
(7, 70, 261, 262, NULL, '2019-06-26 17:00:00', '2019-06-24 07:30:01', '2019-06-24 07:45:08', 2, 1, '');

-- --------------------------------------------------------



CREATE TABLE `category` (
  `id` int(11) NOT NULL,
  `type` varchar(100) DEFAULT NULL,
  `parent_id` int(11) NOT NULL DEFAULT '0',
  `title` varchar(255) NOT NULL DEFAULT '',
  `alias` varchar(255) DEFAULT '',
  `image` varchar(255) DEFAULT '',
  `description` text,
  `state` tinyint(1) NOT NULL DEFAULT '1',
  `metadesc` varchar(250) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `featured` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



INSERT INTO `category` (`id`, `type`, `parent_id`, `title`, `alias`, `image`, `description`, `state`, `metadesc`, `created`, `featured`) VALUES
(114, 'facility', 0, 'Style architectural', 'style-architectural', '', NULL, 0, NULL, NULL, NULL),
(116, 'facility', 114, 'Maison ancienne', 'maison-ancienne', '', NULL, 1, NULL, NULL, NULL),
(118, 'facility', 114, 'Contemporain', 'contemporain', '', NULL, 1, NULL, NULL, NULL),
(119, 'facility', 114, 'Maison libre des trois côtés', 'maison-libre-des-trois-côtés', '', NULL, 1, NULL, NULL, NULL),
(120, 'facility', 114, 'Maison à plusieurs étages', 'maison-à-plusieurs-étages', '', NULL, 1, NULL, NULL, NULL),
(121, 'facility', 114, 'Immeuble ancien', 'immeuble-ancien', '', NULL, 1, NULL, NULL, NULL),
(122, 'facility', 114, 'Contemporain', 'contemporain', '', NULL, 1, NULL, NULL, NULL),
(123, 'facility', 114, 'Maison mitoyenne', 'maison-mitoyenne', '', NULL, 1, NULL, NULL, NULL),
(124, 'facility', 114, 'Maison avec grenier aménagé', 'maison-avec-grenier-aménagé', '', NULL, 1, NULL, NULL, NULL),
(125, 'facility', 114, 'Nouvel immeuble', 'nouvel-immeuble', '', NULL, 1, NULL, NULL, NULL),
(126, 'facility', 0, 'Caractéristiques de l\'immeuble', '', '', NULL, 0, NULL, NULL, NULL),
(127, 'facility', 126, 'Accessible aux chaises roulantes', '', '', NULL, 1, NULL, NULL, NULL),
(128, 'facility', 126, 'Animaux non autorisés', '', '', NULL, 1, NULL, NULL, NULL),
(129, 'facility', 0, 'Caractéristiques extérieures', '', '', NULL, 0, NULL, NULL, NULL),
(130, 'facility', 129, 'Garage 2 voitures', '', '', NULL, 1, NULL, NULL, NULL),
(131, 'facility', 129, 'Vues extérieures', '', '', NULL, 1, NULL, NULL, NULL),
(132, 'facility', 129, 'Garage séparé', '', '', NULL, 1, NULL, NULL, NULL),
(133, 'facility', 129, 'Jardin', '', '', NULL, 1, NULL, NULL, NULL),
(134, 'facility', 129, 'Isolé', '', '', NULL, 1, NULL, NULL, NULL),
(135, 'facility', 129, 'Parking privé', '', '', NULL, 1, NULL, NULL, NULL),
(136, 'facility', 129, 'Terrasse', '', '', NULL, 1, NULL, NULL, NULL),
(137, 'facility', 129, 'Balcon', '', '', NULL, 1, NULL, NULL, NULL),
(138, 'facility', 129, 'Garage', '', '', NULL, 1, NULL, NULL, NULL),
(139, 'facility', 129, 'Porte de garage automatisée', '', '', NULL, 1, NULL, NULL, NULL),
(140, 'facility', 129, 'Veranda', '', '', NULL, 1, NULL, NULL, NULL),
(141, 'facility', 129, 'Parking', '', '', NULL, 1, NULL, NULL, NULL),
(142, 'facility', 129, 'Piscine', '', '', NULL, 1, NULL, NULL, NULL),
(143, 'facility', 0, 'Général', '', '', NULL, 0, NULL, NULL, NULL),
(144, 'facility', 143, 'Ascenseur', '', '', NULL, 1, NULL, NULL, NULL),
(145, 'facility', 143, 'Rénové', '', '', NULL, 1, NULL, NULL, NULL),
(146, 'facility', 0, 'Caractéristiques intérieures', '', '', NULL, 1, NULL, NULL, NULL),
(147, 'facility', 146, 'Baie vitrée', '', '', NULL, 0, NULL, NULL, NULL),
(148, 'facility', 146, 'Feu ouvert / cheminée', '', '', NULL, 1, NULL, NULL, NULL),
(149, 'facility', 146, 'Meublé', '', '', NULL, 0, NULL, NULL, NULL),
(150, 'facility', 146, 'Cuisine - américaine', '', '', NULL, 0, NULL, NULL, NULL),
(151, 'facility', 146, 'Bibliothèque', '', '', NULL, 1, NULL, NULL, NULL),
(152, 'facility', 146, 'Chauffage au mazout', '', '', NULL, 0, NULL, NULL, NULL),
(153, 'facility', 146, 'Chauffage énergie solaire', '', '', NULL, 0, NULL, NULL, NULL),
(154, 'facility', 146, 'Buanderie', '', '', NULL, 0, NULL, NULL, NULL),
(155, 'facility', 146, 'Chauffage électrique', '', '', NULL, 0, NULL, NULL, NULL),
(156, 'facility', 146, 'Sol - Parquet', '', '', NULL, 0, NULL, NULL, NULL),
(157, 'facility', 146, 'Cuisine - coin repas', '', '', NULL, 0, NULL, NULL, NULL),
(158, 'facility', 146, 'Cuisine - séparée', '', '', NULL, 0, NULL, NULL, NULL),
(159, 'facility', 146, 'Chambre de bonne', '', '', NULL, 0, NULL, NULL, NULL),
(160, 'facility', 146, 'Salle de jeux', '', '', NULL, 0, NULL, NULL, NULL),
(161, 'facility', 146, 'Non-meublé', '', '', NULL, 1, NULL, NULL, NULL),
(162, 'facility', 146, 'Buanderie (commune)', '', '', NULL, 0, NULL, NULL, NULL),
(163, 'facility', 0, 'Situation', '', '', NULL, 0, NULL, NULL, NULL),
(164, 'facility', 163, 'Situation calme', '', '', NULL, 1, NULL, NULL, NULL),
(165, 'facility', 163, 'Maison de campagne', '', '', NULL, 1, NULL, NULL, NULL),
(166, 'facility', 163, 'Centre ville', '', '', NULL, 1, NULL, NULL, NULL),
(167, 'facility', 163, 'Isolé', '', '', NULL, 1, NULL, NULL, NULL),
(168, 'facility', 163, 'Bus à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(169, 'facility', 163, 'Autoroute à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(170, 'facility', 163, 'Autoroute à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(171, 'facility', 163, 'Transports publics à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(172, 'facility', 163, 'Ecoles à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(173, 'facility', 163, 'Forêt à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(174, 'facility', 163, 'Sur une route peu frequentée', '', '', NULL, 1, NULL, NULL, NULL),
(175, 'facility', 163, 'Vue dégagée', '', '', NULL, 1, NULL, NULL, NULL),
(176, 'facility', 163, 'Plage', '', '', NULL, 1, NULL, NULL, NULL),
(177, 'facility', 163, 'Campagne', '', '', NULL, 1, NULL, NULL, NULL),
(178, 'facility', 163, 'Quartier dynamique', '', '', NULL, 1, NULL, NULL, NULL),
(179, 'facility', 163, 'Montagnes', '', '', NULL, 1, NULL, NULL, NULL),
(180, 'facility', 163, 'Centre de Fitness à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(181, 'facility', 163, 'Hôpital à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(182, 'facility', 163, 'Parc à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(183, 'facility', 163, 'Gare à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(184, 'facility', 163, 'Commerces à proximité', '', '', NULL, 1, NULL, NULL, NULL),
(185, 'facility', 163, 'Sur une route fréquentée', '', '', NULL, 1, NULL, NULL, NULL),
(186, 'facility', 163, 'Superbe vue', '', '', NULL, 1, NULL, NULL, NULL),
(187, 'facility', 0, 'Orientation', '', '', NULL, 1, NULL, NULL, NULL),
(188, 'facility', 187, 'Est', '', '', NULL, 1, NULL, NULL, NULL),
(189, 'facility', 187, 'Nord est', '', '', NULL, 1, NULL, NULL, NULL),
(190, 'facility', 187, 'Sud', '', '', NULL, 1, NULL, NULL, NULL),
(191, 'facility', 187, 'Sud ouest', '', '', NULL, 1, NULL, NULL, NULL),
(192, 'facility', 187, 'Nord', '', '', NULL, 1, NULL, NULL, NULL),
(193, 'facility', 187, 'Nord-ouest', '', '', NULL, 1, NULL, NULL, NULL),
(194, 'facility', 187, 'Sud est', '', '', NULL, 1, NULL, NULL, NULL),
(195, 'facility', 187, 'Ouest', '', '', NULL, 1, NULL, NULL, NULL),
(196, 'facility', 0, 'Gaz/eau/électr.', '', '', NULL, 0, NULL, NULL, NULL),
(197, 'facility', 196, 'Télévision par câble', '', '', NULL, 1, NULL, NULL, NULL),
(198, 'facility', 196, 'Satellite', '', '', NULL, 1, NULL, NULL, NULL),
(199, 'facility', 196, 'ADSL', '', '', NULL, 1, NULL, NULL, NULL),
(200, 'facility', 196, 'Jacuzzi', '', '', NULL, 1, NULL, NULL, NULL),
(201, 'facility', 196, 'Capteurs solaires', '', '', NULL, 1, NULL, NULL, NULL),
(202, 'facility', 196, 'Air Conditionné', '', '', NULL, 1, NULL, NULL, NULL),
(203, 'facility', 0, 'Caractéristiques', '', '', NULL, 0, NULL, NULL, NULL),
(204, 'facility', 201, 'Contemporain', '', '', NULL, 1, NULL, NULL, NULL),
(205, 'facility', 203, 'Montagnes', '', '', NULL, 1, NULL, NULL, NULL),
(206, 'facility', 203, 'Chauffage électrique', '', '', NULL, 1, NULL, NULL, NULL),
(207, 'facility', 203, 'Garage', '', '', NULL, 1, NULL, NULL, NULL),
(208, 'facility', 203, 'Vues extérieures', '', '', NULL, 1, NULL, NULL, NULL),
(209, 'facility', 203, 'Immeuble ancien', '', '', NULL, 1, NULL, NULL, NULL),
(210, 'facility', 203, 'Plage', '', '', NULL, 1, NULL, NULL, NULL),
(211, 'facility', 203, 'Cuisine - séparée', '', '', NULL, 1, NULL, NULL, NULL),
(212, 'facility', 203, 'Jardin', '', '', NULL, 1, NULL, NULL, NULL),
(213, 'facility', 203, 'Campagne', '', '', NULL, 1, NULL, NULL, NULL),
(214, 'facility', 203, 'Chauffage au mazout', '', '', NULL, 1, NULL, NULL, NULL),
(215, 'facility', 203, 'Meublé', '', '', NULL, 1, NULL, NULL, NULL),
(216, 'facility', 203, 'Piscine', '', '', NULL, 1, NULL, NULL, NULL),
(217, 'room', 0, 'Type de pièce', '', '', NULL, 0, NULL, NULL, NULL),
(218, 'room', 217, 'Boudoir', '', '', NULL, 0, NULL, NULL, NULL),
(219, 'room', 217, 'Cellier', '', '', NULL, 1, NULL, NULL, NULL),
(220, 'room', 217, 'Dressing', '', '', NULL, 1, NULL, NULL, NULL),
(221, 'room', 217, 'Hall d\'entrée', '', '', NULL, 1, NULL, NULL, NULL),
(222, 'room', 217, 'pièce en L', '', '', NULL, 0, NULL, NULL, NULL),
(223, 'room', 217, 'pièce en T', '', '', NULL, 0, NULL, NULL, NULL),
(224, 'room', 217, 'pièce en U', '', '', NULL, 0, NULL, NULL, NULL),
(225, 'room', 217, 'pièce en Z', '', '', NULL, 0, NULL, NULL, NULL),
(226, 'room', 217, 'Salle à déjeuner', '', '', NULL, 0, NULL, NULL, NULL),
(227, 'room', 217, 'Salle de jeu', '', '', NULL, 0, NULL, NULL, NULL),
(228, 'room', 217, 'Salle de repos', '', '', NULL, 0, NULL, NULL, NULL),
(229, 'room', 217, 'Salle des fêtes', '', '', NULL, 0, NULL, NULL, NULL),
(230, 'room', 217, 'Suite parentale', '', '', NULL, 1, NULL, NULL, NULL),
(231, 'room', 217, 'Balcon/terrasse', '', '', NULL, 0, NULL, NULL, NULL),
(232, 'room', 217, 'Bibliothèque', '', '', NULL, 0, NULL, NULL, NULL),
(233, 'room', 217, 'Buanderie', '', '', NULL, 1, NULL, NULL, NULL),
(234, 'room', 217, 'Bureau', '', '', NULL, 1, NULL, NULL, NULL),
(235, 'room', 217, 'Cave', '', '', NULL, 1, NULL, NULL, NULL),
(236, 'room', 217, 'Cave (Bar)', '', '', NULL, 0, NULL, NULL, NULL),
(237, 'room', 217, 'Chambre à coucher\r\n', '', '', NULL, 0, NULL, NULL, NULL),
(238, 'room', 217, 'Chambre principale\r\n', '', '', NULL, 0, NULL, NULL, NULL),
(239, 'room', 217, 'Salon', '', '', NULL, 0, NULL, NULL, NULL),
(240, 'room', 217, 'Chaufferie', '', '', NULL, 0, NULL, NULL, NULL),
(241, 'room', 217, 'Cuisine', '', '', NULL, 1, NULL, NULL, NULL),
(242, 'room', 217, 'Salle de jeux', '', '', NULL, 1, NULL, NULL, NULL),
(243, 'room', 217, 'Salle de bains en-suite', '', '', NULL, 0, NULL, NULL, NULL),
(244, 'room', 217, 'Garage/Parking', '', '', NULL, 0, NULL, NULL, NULL),
(245, 'room', 217, 'Grenier', '', '', NULL, 0, NULL, NULL, NULL),
(246, 'room', 217, 'Loggia', '', '', NULL, 0, NULL, NULL, NULL),
(247, 'room', 217, 'Pièce donnant sur jardin', '', '', NULL, 0, NULL, NULL, NULL),
(248, 'room', 217, 'magazin à bois/charbon', '', '', NULL, 0, NULL, NULL, NULL),
(249, 'room', 217, 'Pièce de protection civile', '', '', NULL, 0, NULL, NULL, NULL),
(250, 'room', 217, 'Séchoir pour linge', '', '', NULL, 0, NULL, NULL, NULL),
(251, 'room', 217, 'Réserve', '', '', NULL, 0, NULL, NULL, NULL),
(252, 'room', 217, 'Salle à manger', '', '', NULL, 1, NULL, NULL, NULL),
(253, 'room', 217, 'Salle de bain', '', '', NULL, 1, NULL, NULL, NULL),
(254, 'room', 217, 'Salon-cuisine', '', '', NULL, 0, NULL, NULL, NULL),
(255, 'room', 217, 'Salon/Salle à manger', '', '', NULL, 1, NULL, NULL, NULL),
(256, 'room', 217, 'Salle de douche', '', '', NULL, 1, NULL, NULL, NULL),
(257, 'room', 217, 'Salle de fitness', '', '', NULL, 1, NULL, NULL, NULL),
(258, 'room', 217, 'Pièce à réservoir', '', '', NULL, 0, NULL, NULL, NULL),
(259, 'room', 217, 'Salle de séjour', '', '', NULL, 0, NULL, NULL, NULL),
(260, 'room', 217, 'Salon', '', '', NULL, 0, NULL, NULL, NULL),
(261, 'room', 217, 'Salle de famille', '', '', NULL, 0, NULL, NULL, NULL),
(262, 'room', 217, 'Salon', '', '', NULL, 0, NULL, NULL, NULL),
(263, 'room', 217, 'Sauna', '', '', NULL, 0, NULL, NULL, NULL),
(264, 'room', 217, 'Serre', '', '', NULL, 0, NULL, NULL, NULL),
(265, 'room', 217, 'Hall d\'entrée', '', '', NULL, 1, NULL, NULL, NULL),
(266, 'room', 217, 'Jardin', '', '', NULL, 1, NULL, NULL, NULL),
(267, 'room', 217, 'WC', '', '', NULL, 0, NULL, NULL, NULL),
(268, 'room', 217, 'Vestibule', '', '', NULL, 0, NULL, NULL, NULL),
(269, 'room', 217, 'Solarium', '', '', NULL, 0, NULL, NULL, NULL),
(270, 'room', 217, 'Atelier', '', '', NULL, 0, NULL, NULL, NULL),
(271, 'room', 217, 'Autre', '', '', NULL, 0, NULL, NULL, NULL),
(272, 'room', 217, 'Altana', '', '', NULL, 0, NULL, NULL, NULL),
(273, 'room', 217, 'Den', '', '', NULL, 0, NULL, NULL, NULL),
(274, 'room', 217, 'Maid\'s Room', '', '', NULL, 0, NULL, NULL, NULL),
(275, 'room', 217, 'Réserve', '', '', NULL, 0, NULL, NULL, NULL),
(276, 'room', 217, 'Toy Room', '', '', NULL, 0, NULL, NULL, NULL),
(277, 'type_property', 0, 'Appartement', '', '', NULL, 1, NULL, NULL, NULL),
(280, 'type_property', 277, 'Penthouse', '', '', NULL, 1, NULL, NULL, NULL),
(281, 'type_property', 277, 'Maison de rapport', '', '', NULL, 1, NULL, NULL, NULL),
(282, 'type_property', 277, 'Duplex', '', '', NULL, 1, NULL, NULL, NULL),
(283, 'type_property', 277, 'Studio', '', '', NULL, 1, NULL, NULL, NULL),
(284, 'type_property', 0, 'Maison', '', '', NULL, 1, NULL, NULL, NULL),
(285, 'type_property', 284, 'Chalet', '', '', NULL, 1, NULL, NULL, NULL),
(286, 'type_property', 284, 'Maison', '', '', NULL, 1, NULL, NULL, NULL),
(287, 'type_property', 284, 'Maison jumelée', '', '', NULL, 1, NULL, NULL, NULL),
(288, 'type_property', 284, 'Chalet individuel', '', '', NULL, 1, NULL, NULL, NULL),
(289, 'type_property', 284, 'Chambre', '', '', NULL, 1, NULL, NULL, NULL),
(290, 'type_property', 284, 'Maison mitoyenne', '', '', NULL, 1, NULL, NULL, NULL),
(291, 'type_property', 284, 'Maison-villa', '', '', NULL, 1, NULL, NULL, NULL),
(292, 'type_property', 0, 'Terrain', '', '', NULL, 1, NULL, NULL, NULL),
(293, 'type_property', 0, 'Garage', '', '', NULL, 1, NULL, NULL, NULL),
(295, 'cat_property', 294, 'Tout', '', '', NULL, 1, NULL, NULL, NULL),
(296, 'cat_property', 294, 'De luxe', '', '', NULL, 1, NULL, NULL, NULL),
(297, 'cat_property', 294, 'Ferme', '', '', NULL, 1, NULL, NULL, NULL),
(298, 'cat_property', 294, 'Industriel', '', '', NULL, 1, NULL, NULL, NULL),
(299, 'cat_property', 294, 'Investissement', '', '', NULL, 1, NULL, NULL, NULL),
(300, 'cat_property', 294, 'Nouveau développement', '', '', NULL, 1, NULL, NULL, NULL),
(301, 'cat_property', 294, 'Propriétaire privé', '', '', NULL, 1, NULL, NULL, NULL),
(302, 'cat_property', 294, 'Propriété communale', '', '', NULL, 1, NULL, NULL, NULL),
(303, 'cat_property', 294, 'Recréation', '', '', NULL, 1, NULL, NULL, NULL),
(304, 'cat_property', 294, 'Résidence fermée', '', '', NULL, 1, NULL, NULL, NULL),
(305, 'cat_property', 294, 'Retraite', '', '', NULL, 1, NULL, NULL, NULL),
(306, 'cat_property', 294, 'Subventionné', '', '', NULL, 1, NULL, NULL, NULL),
(307, 'cat_property', 294, 'Terrain', '', '', NULL, 1, NULL, NULL, NULL),
(308, 'cat_property', 294, 'The RE/MAX Collection', '', '', NULL, 1, NULL, NULL, NULL),
(309, 'cat_property', 294, 'Vente de fonds de commerce', '', '', NULL, 1, NULL, NULL, NULL),
(310, 'cat_property', 294, 'Villégiature', '', '', NULL, 1, NULL, NULL, NULL),
(312, 'facility', 146, 'Parquet', '', '', NULL, 1, NULL, NULL, NULL),
(313, 'facility', 146, 'Marbre', '', '', NULL, 1, NULL, NULL, NULL),
(314, 'facility', 146, 'Faux', '', '', NULL, 1, NULL, NULL, NULL),
(315, 'facility', 146, 'Carrelage', '', '', NULL, 1, NULL, NULL, NULL),
(316, 'facility', 146, 'Cuisine équipée', '', '', NULL, 1, NULL, NULL, NULL),
(317, 'facility', 146, 'Cuisine ouverte', '', '', NULL, 1, NULL, NULL, NULL),
(318, 'facility', 146, 'Cuisine indépendante', '', '', NULL, 1, NULL, NULL, NULL),
(319, 'facility', 146, 'Jacuzzi', '', '', NULL, 1, NULL, NULL, NULL),
(320, 'facility', 146, 'Sauna', '', '', NULL, 1, NULL, NULL, NULL),
(321, 'facility', 146, 'Hammam', '', '', NULL, 1, NULL, NULL, NULL),
(322, 'facility', 146, 'Placard', '', '', NULL, 1, NULL, NULL, NULL),
(323, 'room', 217, 'Hall de nuit', '', '', NULL, 1, NULL, NULL, NULL),
(324, 'room', 217, 'Living', '', '', NULL, 1, NULL, NULL, NULL),
(325, 'room', 217, 'Véranda', '', '', NULL, 1, NULL, NULL, NULL),
(326, 'room', 217, 'Balcon', '', '', NULL, 1, NULL, NULL, NULL),
(327, 'room', 217, 'Terrasse', '', '', NULL, 1, NULL, NULL, NULL),
(328, 'room', 217, 'Double garage en enfilade', '', '', NULL, 1, NULL, NULL, NULL),
(329, 'room', 217, 'Double garage côte à côte\r\n', '', '', NULL, 1, NULL, NULL, NULL),
(330, 'room', 217, 'Salle de sport\r\n', '', '', NULL, 1, NULL, NULL, NULL),
(331, 'room', 217, 'Chambre', '', '', NULL, 1, NULL, NULL, NULL),
(332, 'room', 217, 'Local technique', '', '', NULL, 1, NULL, NULL, NULL),
(333, 'room', 217, 'Salon/ Salle à manger', '', '', NULL, 1, NULL, NULL, NULL),
(334, 'room', 217, 'Grenier aménagé', '', '', NULL, 1, NULL, NULL, NULL),
(335, 'room', 217, 'Grenier aménageable', '', '', NULL, 1, NULL, NULL, NULL),
(336, 'facility', 146, 'Armoire intégrée\r\n', '', '', NULL, 1, NULL, NULL, NULL),
(337, 'facility', 146, 'Non meublé', '', '', NULL, 1, NULL, NULL, NULL);

-- --------------------------------------------------------

--
-- Cấu trúc bảng cho bảng `city`
--

CREATE TABLE `city` (
  `id` int(11) NOT NULL,
  `lft` int(11) DEFAULT NULL,
  `rgt` int(11) DEFAULT NULL,
  `path` varchar(200) DEFAULT NULL,
  `access` tinyint(4) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `title` varchar(200) DEFAULT NULL,
  `value` varchar(200) DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `images` tinytext,
  `country_id` int(11) DEFAULT NULL,
  `type` varchar(500) DEFAULT NULL,
  `alias` varchar(200) DEFAULT NULL,
  `ordering` int(11) DEFAULT NULL,
  `code` varchar(4) DEFAULT NULL,
  `state` tinyint(11) DEFAULT NULL,
  `longitude` float DEFAULT NULL,
  `latitude` float DEFAULT NULL,
  `state_id` smallint(6) DEFAULT NULL,
  `desc` text,
  `metakey` tinytext,
  `metadesc` mediumtext,
  `province` tinyint(4) DEFAULT NULL,
  `air` tinyint(4) DEFAULT NULL,
  `bus` tinyint(4) DEFAULT NULL,
  `level` int(11) DEFAULT NULL,
  `intro` text,
  `params` text
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

--
-- Đang đổ dữ liệu cho bảng `city`
--

INSERT INTO `city` (`id`, `lft`, `rgt`, `path`, `access`, `parent_id`, `title`, `value`, `image`, `images`, `country_id`, `type`, `alias`, `ordering`, `code`, `state`, `longitude`, `latitude`, `state_id`, `desc`, `metakey`, `metadesc`, `province`, `air`, `bus`, `level`, `intro`, `params`) VALUES
(513, NULL, NULL, NULL, NULL, NULL, 'Bertrange', NULL, NULL, NULL, NULL, 'center', 'bertrange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(514, NULL, NULL, NULL, NULL, NULL, 'Bissen', NULL, NULL, NULL, NULL, 'center', 'bissen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(515, NULL, NULL, NULL, NULL, NULL, 'Colmar-Berg', NULL, NULL, NULL, NULL, 'center', 'colmar-berg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(516, NULL, NULL, NULL, NULL, NULL, 'Contern', NULL, NULL, NULL, NULL, 'center', 'contern', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(517, NULL, NULL, NULL, NULL, NULL, 'Fischbach', NULL, NULL, NULL, NULL, 'center', 'fischbach', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(518, NULL, NULL, NULL, NULL, NULL, 'Heffingen', NULL, NULL, NULL, NULL, 'center', 'heffingen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(519, NULL, NULL, NULL, NULL, NULL, 'Helperknapp', NULL, NULL, NULL, NULL, 'center', 'helperknapp', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(520, NULL, NULL, NULL, NULL, NULL, 'Hesperange', NULL, NULL, NULL, NULL, 'center', 'hesperange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(521, NULL, NULL, NULL, NULL, NULL, 'Larochette', NULL, NULL, NULL, NULL, 'center', 'larochette', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(522, NULL, NULL, NULL, NULL, NULL, 'Lintgen', NULL, NULL, NULL, NULL, 'center', 'lintgen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(523, NULL, NULL, NULL, NULL, NULL, 'Lorentzweiler', NULL, NULL, NULL, NULL, 'center', 'lorentzweiler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(524, NULL, NULL, NULL, NULL, NULL, 'Luxembourg (Capitale)', NULL, NULL, NULL, NULL, 'center', 'luxembourg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(525, NULL, NULL, NULL, NULL, NULL, 'Mersch', NULL, NULL, NULL, NULL, 'center', 'mersch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(526, NULL, NULL, NULL, NULL, NULL, 'Niederanven', NULL, NULL, NULL, NULL, 'center', 'niederanven', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(527, NULL, NULL, NULL, NULL, NULL, 'Nommern', NULL, NULL, NULL, NULL, 'center', 'nommern', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(528, NULL, NULL, NULL, NULL, NULL, 'Sandweiler', NULL, NULL, NULL, NULL, 'center', 'sandweiler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(529, NULL, NULL, NULL, NULL, NULL, 'Schuttrange', NULL, NULL, NULL, NULL, 'center', 'schuttrange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(530, NULL, NULL, NULL, NULL, NULL, 'Steinsel', NULL, NULL, NULL, NULL, 'center', 'steinsel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(531, NULL, NULL, NULL, NULL, NULL, 'Strassen', NULL, NULL, NULL, NULL, 'center', 'strassen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(532, NULL, NULL, NULL, NULL, NULL, 'Walferdange', NULL, NULL, NULL, NULL, 'center', 'walferdange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(533, NULL, NULL, NULL, NULL, NULL, 'Weiler-la-Tour', NULL, NULL, NULL, NULL, 'center', 'weiler-la-tour', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(534, NULL, NULL, NULL, NULL, NULL, 'Beaufort', NULL, NULL, NULL, NULL, 'east', 'beaufort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(535, NULL, NULL, NULL, NULL, NULL, 'Bech', NULL, NULL, NULL, NULL, 'east', 'bech', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(536, NULL, NULL, NULL, NULL, NULL, 'Berdorf', NULL, NULL, NULL, NULL, 'east', 'berdorf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(537, NULL, NULL, NULL, NULL, NULL, 'Betzdorf', NULL, NULL, NULL, NULL, 'east', 'betzdorf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(538, NULL, NULL, NULL, NULL, NULL, 'Biwer', NULL, NULL, NULL, NULL, 'east', 'biwer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(539, NULL, NULL, NULL, NULL, NULL, 'Bous', NULL, NULL, NULL, NULL, 'east', 'bous', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(540, NULL, NULL, NULL, NULL, NULL, 'Consdorf', NULL, NULL, NULL, NULL, 'east', 'consdorf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(541, NULL, NULL, NULL, NULL, NULL, 'Dalheim', NULL, NULL, NULL, NULL, 'east', 'dalheim', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(542, NULL, NULL, NULL, NULL, NULL, 'Echternach', NULL, NULL, NULL, NULL, 'east', 'echternach', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(543, NULL, NULL, NULL, NULL, NULL, 'Flaxweiler', NULL, NULL, NULL, NULL, 'east', 'flaxweiler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(544, NULL, NULL, NULL, NULL, NULL, 'Grevenmacher', NULL, NULL, NULL, NULL, 'east', 'grevenmacher', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(545, NULL, NULL, NULL, NULL, NULL, 'Junglinster', NULL, NULL, NULL, NULL, 'east', 'junglinster', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(546, NULL, NULL, NULL, NULL, NULL, 'Lenningen', NULL, NULL, NULL, NULL, 'east', 'lenningen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(547, NULL, NULL, NULL, NULL, NULL, 'Manternach', NULL, NULL, NULL, NULL, 'east', 'manternach', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(548, NULL, NULL, NULL, NULL, NULL, 'Mertert', NULL, NULL, NULL, NULL, 'east', 'mertert', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(549, NULL, NULL, NULL, NULL, NULL, 'Mondorf-les-Bains', NULL, NULL, NULL, NULL, 'east', 'mondorf-les-bains', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(550, NULL, NULL, NULL, NULL, NULL, 'Remich', NULL, NULL, NULL, NULL, 'east', 'remich', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(551, NULL, NULL, NULL, NULL, NULL, 'Rosport-Mompach', NULL, NULL, NULL, NULL, 'east', 'rosport-mompach', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(552, NULL, NULL, NULL, NULL, NULL, 'Schengen', NULL, NULL, NULL, NULL, 'east', 'schengen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(553, NULL, NULL, NULL, NULL, NULL, 'Stadtbredimus', NULL, NULL, NULL, NULL, 'east', 'stadtbredimus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(554, NULL, NULL, NULL, NULL, NULL, 'Waldbillig', NULL, NULL, NULL, NULL, 'east', 'waldbillig', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(555, NULL, NULL, NULL, NULL, NULL, 'Waldbredimus', NULL, NULL, NULL, NULL, 'east', 'waldbredimus', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(556, NULL, NULL, NULL, NULL, NULL, 'Wormeldange', NULL, NULL, NULL, NULL, 'east', 'wormeldange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(557, NULL, NULL, NULL, NULL, NULL, 'Bettendorf', NULL, NULL, NULL, NULL, 'north', 'bettendorf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(558, NULL, NULL, NULL, NULL, NULL, 'Boulaide', NULL, NULL, NULL, NULL, 'north', 'boulaide', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(559, NULL, NULL, NULL, NULL, NULL, 'Bourscheid', NULL, NULL, NULL, NULL, 'north', 'bourscheid', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(560, NULL, NULL, NULL, NULL, NULL, 'Diekirch', NULL, NULL, NULL, NULL, 'north', 'diekirch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(561, NULL, NULL, NULL, NULL, NULL, 'Erpeldange', NULL, NULL, NULL, NULL, 'north', 'erpeldange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(562, NULL, NULL, NULL, NULL, NULL, 'Erpeldange-sur-Sûre', NULL, NULL, NULL, NULL, 'north', 'erpeldange-sur-sure', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(563, NULL, NULL, NULL, NULL, NULL, 'Esch-sur-Sûre', NULL, NULL, NULL, NULL, 'north', 'esch-sur-sure', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(564, NULL, NULL, NULL, NULL, NULL, 'Ettelbrück', NULL, NULL, NULL, NULL, 'north', 'ettelbruck', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(565, NULL, NULL, NULL, NULL, NULL, 'Feulen', NULL, NULL, NULL, NULL, 'east', 'feulen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(566, NULL, NULL, NULL, NULL, NULL, 'Goesdorf', NULL, NULL, NULL, NULL, 'north', 'goesdorf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(567, NULL, NULL, NULL, NULL, NULL, 'Kiischpelt', NULL, NULL, NULL, NULL, 'north', 'kiischpelt', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(568, NULL, NULL, NULL, NULL, NULL, 'Lac de la Haute-Sûre', NULL, NULL, NULL, NULL, 'north', 'lac-de-la-haute-sure', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(569, NULL, NULL, NULL, NULL, NULL, 'Mertzig', NULL, NULL, NULL, NULL, 'north', 'mertzig', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(570, NULL, NULL, NULL, NULL, NULL, 'Parc-Hosingen', NULL, NULL, NULL, NULL, 'north', 'parc-hosingen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(571, NULL, NULL, NULL, NULL, NULL, 'Putscheid', NULL, NULL, NULL, NULL, 'north', 'putscheid', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(572, NULL, NULL, NULL, NULL, NULL, 'Reisdorf', NULL, NULL, NULL, NULL, 'north', 'reisdorf', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(573, NULL, NULL, NULL, NULL, NULL, 'Schieren', NULL, NULL, NULL, NULL, 'north', 'schieren', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(574, NULL, NULL, NULL, NULL, NULL, 'Tandel', NULL, NULL, NULL, NULL, 'north', 'tandel', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(575, NULL, NULL, NULL, NULL, NULL, 'Troisvierges', NULL, NULL, NULL, NULL, 'north', 'troisvierges', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(576, NULL, NULL, NULL, NULL, NULL, 'Vallée de l’Ernz', NULL, NULL, NULL, NULL, 'north', 'vallee-de-lernz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(577, NULL, NULL, NULL, NULL, NULL, 'Vianden', NULL, NULL, NULL, NULL, 'north', 'vianden', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(578, NULL, NULL, NULL, NULL, NULL, 'Weiswampach', NULL, NULL, NULL, NULL, 'north', 'weiswampach', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(579, NULL, NULL, NULL, NULL, NULL, 'Wiltz', NULL, NULL, NULL, NULL, 'north', 'wiltz', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(580, NULL, NULL, NULL, NULL, NULL, 'Wincrange', NULL, NULL, NULL, NULL, 'north', 'wincrange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(581, NULL, NULL, NULL, NULL, NULL, 'Winseler', NULL, NULL, NULL, NULL, 'north', 'winseler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(582, NULL, NULL, NULL, NULL, NULL, 'Bettembourg', NULL, NULL, NULL, NULL, 'south', 'bettembourg', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(583, NULL, NULL, NULL, NULL, NULL, 'Differdange', NULL, NULL, NULL, NULL, 'south', 'differdange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(584, NULL, NULL, NULL, NULL, NULL, 'Dudelange', NULL, NULL, NULL, NULL, 'south', 'dudelange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(585, NULL, NULL, NULL, NULL, NULL, 'Esch-sur-Alzette', NULL, NULL, NULL, NULL, 'south', 'esch-sur-alzette', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(586, NULL, NULL, NULL, NULL, NULL, 'Frisange', NULL, NULL, NULL, NULL, 'south', 'frisange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(587, NULL, NULL, NULL, NULL, NULL, 'Kayl', NULL, NULL, NULL, NULL, 'south', 'kayl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(588, NULL, NULL, NULL, NULL, NULL, 'Leudelange', NULL, NULL, NULL, NULL, 'south', 'leudelange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(589, NULL, NULL, NULL, NULL, NULL, 'Mondercange', NULL, NULL, NULL, NULL, 'south', 'mondercange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(590, NULL, NULL, NULL, NULL, NULL, 'Pétange', NULL, NULL, NULL, NULL, 'south', 'petange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(591, NULL, NULL, NULL, NULL, NULL, 'Reckange-sur-Mess', NULL, NULL, NULL, NULL, 'south', 'reckange-sur-mess', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(592, NULL, NULL, NULL, NULL, NULL, 'Roeser', NULL, NULL, NULL, NULL, 'south', 'roeser', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(593, NULL, NULL, NULL, NULL, NULL, 'Rumelange', NULL, NULL, NULL, NULL, 'south', 'rumelange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(594, NULL, NULL, NULL, NULL, NULL, 'Sanem', NULL, NULL, NULL, NULL, 'south', 'sanem', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(595, NULL, NULL, NULL, NULL, NULL, 'Schifflange', NULL, NULL, NULL, NULL, 'south', 'schifflange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(596, NULL, NULL, NULL, NULL, NULL, 'Beckerich', NULL, NULL, NULL, NULL, 'west', 'beckerich', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(597, NULL, NULL, NULL, NULL, NULL, 'Dippach', NULL, NULL, NULL, NULL, 'west', 'dippach', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(598, NULL, NULL, NULL, NULL, NULL, 'Ell', NULL, NULL, NULL, NULL, 'west', 'ell', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(599, NULL, NULL, NULL, NULL, NULL, 'Garnich', NULL, NULL, NULL, NULL, 'west', 'garnich', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(600, NULL, NULL, NULL, NULL, NULL, 'Grosbous', NULL, NULL, NULL, NULL, 'west', 'grosbous', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(602, NULL, NULL, NULL, NULL, NULL, 'Habscht', NULL, NULL, NULL, NULL, 'west', 'habscht', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(603, NULL, NULL, NULL, NULL, NULL, 'Käerjeng', NULL, NULL, NULL, NULL, 'west', 'kaerjeng', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(604, NULL, NULL, NULL, NULL, NULL, 'Kapweiler', NULL, NULL, NULL, NULL, 'west', 'kapweiler', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(605, NULL, NULL, NULL, NULL, NULL, 'Kehlen', NULL, NULL, NULL, NULL, 'west', 'kehlen', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(606, NULL, NULL, NULL, NULL, NULL, 'Koerich', NULL, NULL, NULL, NULL, 'west', 'koerich', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(607, NULL, NULL, NULL, NULL, NULL, 'Kopstal', NULL, NULL, NULL, NULL, 'west', 'kopstal', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(608, NULL, NULL, NULL, NULL, NULL, 'Mamer', NULL, NULL, NULL, NULL, 'west', 'mamer', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(609, NULL, NULL, NULL, NULL, NULL, 'Préizerdaul', NULL, NULL, NULL, NULL, 'west', 'preizerdaul', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(610, NULL, NULL, NULL, NULL, NULL, 'Rambrouch', NULL, NULL, NULL, NULL, 'west', 'rambrouch', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(611, NULL, NULL, NULL, NULL, NULL, 'Redange', NULL, NULL, NULL, NULL, 'west', 'redange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(612, NULL, NULL, NULL, NULL, NULL, 'Saeul', NULL, NULL, NULL, NULL, 'west', 'saeul', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(613, NULL, NULL, NULL, NULL, NULL, 'Steinfort', NULL, NULL, NULL, NULL, 'west', 'steinfort', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(614, NULL, NULL, NULL, NULL, NULL, 'Useldange', NULL, NULL, NULL, NULL, 'west', 'useldange', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(615, NULL, NULL, NULL, NULL, NULL, 'Vichten', NULL, NULL, NULL, NULL, 'west', 'vichten', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL),
(616, NULL, NULL, NULL, NULL, NULL, 'Wahl', NULL, NULL, NULL, NULL, 'west', 'wahl', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- --------------------------------------------------------




CREATE TABLE `contact` (
  `id` int(11) NOT NULL,
  `account_id` int(11) DEFAULT NULL,
  `firstname` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `lastname` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `address` varchar(400) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `city` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `country_id` text,
  `states` varchar(200) CHARACTER SET utf8 COLLATE utf8_unicode_ci DEFAULT NULL,
  `zip` varchar(20) DEFAULT NULL,
  `telephone` varchar(15) DEFAULT NULL,
  `mobile` varchar(15) DEFAULT NULL,
  `lang` varchar(10) DEFAULT NULL,
  `created` datetime DEFAULT NULL,
  `billing_address` text CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `birthday` datetime DEFAULT NULL,
  `state` tinyint(4) DEFAULT '1',
  `referral_id` int(11) DEFAULT NULL,
  `gender` varchar(11) DEFAULT NULL,
  `group_id` int(11) DEFAULT NULL,
  `params` text,
  `company` varchar(400) DEFAULT NULL,
  `image` varchar(200) DEFAULT NULL,
  `about` text,
  `verifymobile` int(11) DEFAULT NULL,
  `phonecode` varchar(10) DEFAULT NULL,
  `activation` varchar(10) DEFAULT NULL,
  `ratings` varchar(20) DEFAULT NULL,
  `coverphoto` varchar(200) DEFAULT NULL,
  `fbtoken` varchar(200) DEFAULT NULL,
  `streetname` varchar(45) DEFAULT NULL,
  `streetnumber` varchar(45) DEFAULT NULL,
  `title` varchar(45) DEFAULT NULL,
  `typecontact` varchar(45) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `unit` varchar(45) DEFAULT NULL,
  `zipcode` varchar(45) DEFAULT NULL,
  `create_account_id` int(11) DEFAULT NULL,
  `source_prospect` varchar(45) DEFAULT NULL,
  `state_email` tinyint(4) DEFAULT '1'
) ENGINE=MyISAM DEFAULT CHARSET=utf8;



CREATE TABLE `country` (
  `id` int(11) NOT NULL,
  `code` varchar(2) NOT NULL DEFAULT '',
  `name` varchar(100) NOT NULL DEFAULT '',
  `state` varchar(45) DEFAULT NULL,
  `content` varchar(45) DEFAULT NULL,
  `region_id` varchar(45) DEFAULT NULL,
  `flag` varchar(255) NOT NULL,
  `ordering` int(11) NOT NULL,
  `params` text,
  `phone_code` varchar(10) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8;



INSERT INTO `country` (`id`, `code`, `name`, `state`, `content`, `region_id`, `flag`, `ordering`, `params`, `phone_code`) VALUES
(1, '中国', ' CHINA', '1', '', NULL, '', 180, NULL, ''),
(2, 'CA', 'Canada', '1', '', NULL, '', 3, NULL, ''),
(3, 'AF', 'Afghanistan', '1', '', '13', '', 164, NULL, ''),
(4, 'AL', 'Albania', '1', '', NULL, '', 163, NULL, '34'),
(5, 'DZ', 'Algeria', '1', NULL, NULL, '', 162, NULL, ''),
(6, 'DS', 'American Samoa', '1', NULL, NULL, '', 161, NULL, ''),
(7, 'AD', 'Andorra', '1', NULL, NULL, '', 160, NULL, ''),
(8, 'AO', 'Angola', '1', NULL, NULL, '', 159, NULL, ''),
(9, 'AI', 'Anguilla', '1', NULL, NULL, '', 158, NULL, ''),
(10, 'AQ', 'Antarctica', '1', NULL, NULL, '', 157, NULL, ''),
(11, 'AG', 'Antigua and/or Barbuda', '1', NULL, NULL, '', 156, NULL, ''),
(12, 'AR', 'Argentina', '1', NULL, NULL, '', 155, NULL, ''),
(13, 'AM', 'Armenia', '1', NULL, NULL, '', 154, NULL, ''),
(14, 'AW', 'Aruba', '1', NULL, NULL, '', 153, NULL, ''),
(15, 'AU', 'Australia', '1', NULL, NULL, '', 165, NULL, ''),
(16, 'AT', 'Austria', '1', NULL, NULL, '', 166, NULL, ''),
(17, 'AZ', 'Azerbaijan', '1', NULL, NULL, '', 167, NULL, ''),
(18, 'BS', 'Bahamas', '1', NULL, NULL, '', 179, NULL, ''),
(19, 'BH', 'Bahrain', '1', NULL, NULL, '', 178, NULL, ''),
(20, 'BD', 'Bangladesh', '1', NULL, NULL, '', 177, NULL, ''),
(21, 'BB', 'Barbados', '1', NULL, NULL, '', 176, NULL, ''),
(22, 'BY', 'Belarus', '1', NULL, NULL, '', 175, NULL, ''),
(23, 'BE', 'Belgium', '1', NULL, NULL, '', 174, NULL, ''),
(24, 'BZ', 'Belize', '1', NULL, NULL, '', 173, NULL, ''),
(25, 'BJ', 'Benin', '1', NULL, NULL, '', 172, NULL, ''),
(26, 'BM', 'Bermuda', '1', NULL, NULL, '', 171, NULL, ''),
(27, 'BT', 'Bhutan', '1', NULL, NULL, '', 170, NULL, ''),
(28, 'BO', 'Bolivia', '1', NULL, NULL, '', 169, NULL, ''),
(29, 'BA', 'Bosnia and Herzegovina', '1', NULL, NULL, '', 168, NULL, ''),
(30, 'BW', 'Botswana', '1', NULL, NULL, '', 152, NULL, ''),
(31, 'BV', 'Bouvet Island', '1', NULL, NULL, '', 151, NULL, ''),
(32, 'BR', 'Brazil', '1', NULL, NULL, '', 150, NULL, ''),
(33, 'IO', 'British lndian Ocean Territory', '1', NULL, NULL, '', 134, NULL, ''),
(34, 'BN', 'Brunei Darussalam', '1', NULL, NULL, '', 133, NULL, ''),
(35, 'BG', 'Bulgaria', '1', NULL, NULL, '', 132, NULL, ''),
(36, 'BF', 'Burkina Faso', '1', NULL, NULL, '', 131, NULL, ''),
(37, 'BI', 'Burundi', '1', NULL, NULL, '', 130, NULL, ''),
(38, 'KH', 'Cambodia', '1', NULL, NULL, '', 129, NULL, ''),
(39, 'CM', 'Cameroon', '1', NULL, NULL, '', 128, NULL, ''),
(40, 'CV', 'Cape Verde', '1', NULL, NULL, '', 127, NULL, ''),
(41, 'KY', 'Cayman Islands', '1', NULL, NULL, '', 126, NULL, ''),
(42, 'CF', 'Central African Republic', '1', NULL, NULL, '', 125, NULL, ''),
(43, 'TD', 'Chad', '1', NULL, NULL, '', 124, NULL, ''),
(44, 'CL', 'Chile', '1', NULL, NULL, '', 123, NULL, ''),
(45, 'CN', 'China', '1', '', NULL, '', 135, NULL, ''),
(46, 'CX', 'Christmas Island', '1', NULL, NULL, '', 136, NULL, ''),
(47, 'CC', 'Cocos (Keeling) Islands', '1', NULL, NULL, '', 137, NULL, ''),
(48, 'CO', 'Colombia', '1', NULL, NULL, '', 149, NULL, ''),
(49, 'KM', 'Comoros', '1', NULL, NULL, '', 148, NULL, ''),
(50, 'CG', 'Congo', '1', NULL, NULL, '', 147, NULL, ''),
(51, 'CK', 'Cook Islands', '1', NULL, NULL, '', 146, NULL, ''),
(52, 'CR', 'Costa Rica', '1', NULL, NULL, '', 145, NULL, ''),
(53, 'HR', 'Croatia (Hrvatska)', '1', '', NULL, '', 144, NULL, ''),
(54, 'CU', 'Cuba', '1', NULL, NULL, '', 143, NULL, ''),
(55, 'CY', 'Cyprus', '1', NULL, NULL, '', 142, NULL, ''),
(56, 'CZ', 'Czech Republic', '1', NULL, NULL, '', 141, NULL, ''),
(57, 'DK', 'Denmark', '1', NULL, NULL, '', 140, NULL, ''),
(58, 'DJ', 'Djibouti', '1', NULL, NULL, '', 139, NULL, ''),
(59, 'DM', 'Dominica', '1', NULL, NULL, '', 138, NULL, ''),
(60, 'DO', 'Dominican Republic', '1', NULL, NULL, '', 122, NULL, ''),
(61, 'TP', 'East Timor', '1', NULL, NULL, '', 181, NULL, ''),
(62, 'EC', 'Ecudaor', '1', NULL, NULL, '', 240, NULL, ''),
(63, 'EG', 'Egypt', '1', NULL, NULL, '', 224, NULL, ''),
(64, 'SV', 'El Salvador', '1', NULL, NULL, '', 223, NULL, ''),
(65, 'GQ', 'Equatorial Guinea', '1', NULL, NULL, '', 222, NULL, ''),
(66, 'ER', 'Eritrea', '1', NULL, NULL, '', 221, NULL, ''),
(67, 'EE', 'Estonia', '1', NULL, NULL, '', 220, NULL, ''),
(68, 'ET', 'Ethiopia', '1', '', NULL, '', 219, NULL, ''),
(69, 'FK', 'Falkland Islands (Malvinas)', '1', NULL, NULL, '', 218, NULL, ''),
(70, 'FO', 'Faroe Islands', '1', NULL, NULL, '', 217, NULL, ''),
(71, 'FJ', 'Fiji', '1', NULL, NULL, '', 216, NULL, ''),
(72, 'FI', 'Finland', '1', NULL, NULL, '', 215, NULL, ''),
(73, 'FR', 'France', '1', NULL, NULL, '', 214, NULL, ''),
(74, 'FX', 'France, Metropolitan', '1', NULL, NULL, '', 213, NULL, ''),
(75, 'GF', 'French Guiana', '1', NULL, NULL, '', 225, NULL, ''),
(76, 'PF', 'French Polynesia', '1', NULL, NULL, '', 226, NULL, ''),
(77, 'TF', 'French Southern Territories', '1', NULL, NULL, '', 227, NULL, ''),
(78, 'GA', 'Gabon', '1', NULL, NULL, '', 239, NULL, ''),
(79, 'GM', 'Gambia', '1', NULL, NULL, '', 238, NULL, ''),
(80, 'GE', 'Georgia', '1', NULL, NULL, '', 237, NULL, ''),
(81, 'DE', 'Germany', '1', NULL, NULL, '', 236, NULL, ''),
(82, 'GH', 'Ghana', '1', NULL, NULL, '', 235, NULL, ''),
(83, 'GI', 'Gibraltar', '1', NULL, NULL, '', 234, NULL, ''),
(84, 'GR', 'Greece', '1', NULL, NULL, '', 233, NULL, ''),
(85, 'GL', 'Greenland', '1', NULL, NULL, '', 232, NULL, ''),
(86, 'GD', 'Grenada', '1', NULL, NULL, '', 231, NULL, ''),
(87, 'GP', 'Guadeloupe', '1', NULL, NULL, '', 230, NULL, ''),
(88, 'GU', 'Guam', '1', NULL, NULL, '', 229, NULL, ''),
(89, 'GT', 'Guatemala', '1', '', NULL, '', 228, NULL, ''),
(90, 'GN', 'Guinea', '1', NULL, NULL, '', 212, NULL, ''),
(91, 'GW', 'Guinea-Bissau', '1', NULL, NULL, '', 211, NULL, ''),
(92, 'GY', 'Guyana', '1', NULL, NULL, '', 210, NULL, ''),
(93, 'HT', 'Haiti', '1', NULL, NULL, '', 194, NULL, ''),
(94, 'HM', 'Heard and Mc Donald Islands', '1', NULL, NULL, '', 193, NULL, ''),
(95, 'HN', 'Honduras', '1', NULL, NULL, '', 192, NULL, ''),
(96, 'HK', 'Hong Kong', '1', NULL, NULL, '', 191, NULL, ''),
(97, 'HU', 'Hungary', '1', NULL, NULL, '', 190, NULL, ''),
(98, 'IS', 'Iceland', '1', NULL, NULL, '', 189, NULL, ''),
(99, 'IN', 'India', '1', NULL, NULL, '', 188, NULL, ''),
(100, 'ID', 'Indonesia', '1', NULL, NULL, '', 187, NULL, ''),
(101, 'IR', 'Iran (Islamic Republic of)', '1', NULL, NULL, '', 186, NULL, ''),
(102, 'IQ', 'Iraq', '1', NULL, NULL, '', 185, NULL, ''),
(103, 'IE', 'Ireland', '1', NULL, NULL, '', 184, NULL, ''),
(104, 'IL', 'Israel', '1', NULL, NULL, '', 183, NULL, ''),
(105, 'IT', 'Italy', '1', NULL, NULL, '', 195, NULL, ''),
(106, 'CI', 'Ivory Coast', '1', NULL, NULL, '', 196, NULL, ''),
(107, 'JM', 'Jamaica', '1', NULL, NULL, '', 197, NULL, ''),
(108, 'JP', 'Japan', '1', NULL, NULL, '', 209, NULL, ''),
(109, 'JO', 'Jordan', '1', NULL, NULL, '', 208, NULL, ''),
(110, 'KZ', 'Kazakhstan', '1', NULL, NULL, '', 207, NULL, ''),
(111, 'KE', 'Kenya', '1', NULL, NULL, '', 206, NULL, ''),
(112, 'KI', 'Kiribati', '1', NULL, NULL, '', 205, NULL, ''),
(113, 'KP', 'Korea, Democratic People\'s Republic of', '1', NULL, NULL, '', 204, NULL, ''),
(114, 'KR', 'Korea, Republic of', '1', NULL, NULL, '', 203, NULL, ''),
(115, 'KW', 'Kuwait', '1', NULL, NULL, '', 202, NULL, ''),
(116, 'KG', 'Kyrgyzstan', '1', NULL, NULL, '', 201, NULL, ''),
(117, 'LA', 'Lao People\'s Democratic Republic', '1', NULL, NULL, '', 200, NULL, ''),
(118, 'LV', 'Latvia', '1', NULL, NULL, '', 199, NULL, ''),
(119, 'LB', 'Lebanon', '1', NULL, NULL, '', 198, NULL, ''),
(120, 'LS', 'Lesotho', '1', NULL, NULL, '', 182, NULL, ''),
(121, 'LR', 'Liberia', '1', NULL, NULL, '', 61, NULL, ''),
(122, 'LY', 'Libyan Arab Jamahiriya', '1', NULL, NULL, '', 45, NULL, ''),
(123, 'LI', 'Liechtenstein', '1', NULL, NULL, '', 44, NULL, ''),
(124, 'LT', 'Lithuania', '1', NULL, NULL, '', 43, NULL, ''),
(125, 'LU', 'Luxembourg', '1', NULL, NULL, '', 42, NULL, ''),
(126, 'MO', 'Macau', '1', NULL, NULL, '', 41, NULL, ''),
(127, 'MK', 'Macedonia', '1', NULL, NULL, '', 40, NULL, ''),
(128, 'MG', 'Madagascar', '1', NULL, NULL, '', 39, NULL, ''),
(129, 'MW', 'Malawi', '1', NULL, NULL, '', 38, NULL, ''),
(130, 'MY', 'Malaysia', '1', NULL, NULL, '', 37, NULL, ''),
(131, 'MV', 'Maldives', '1', NULL, NULL, '', 36, NULL, ''),
(132, 'ML', 'Mali', '1', NULL, NULL, '', 35, NULL, ''),
(133, 'MT', 'Malta', '1', NULL, NULL, '', 34, NULL, ''),
(134, 'MH', 'Marshall Islands', '1', NULL, NULL, '', 46, NULL, ''),
(135, 'MQ', 'Martinique', '1', NULL, NULL, '', 47, NULL, ''),
(136, 'MR', 'Mauritania', '1', NULL, NULL, '', 48, NULL, ''),
(137, 'MU', 'Mauritius', '1', NULL, NULL, '', 60, NULL, ''),
(138, 'TY', 'Mayotte', '1', NULL, NULL, '', 59, NULL, ''),
(139, 'MX', 'Mexico', '1', NULL, NULL, '', 58, NULL, ''),
(140, 'FM', 'Micronesia, Federated States of', '1', NULL, NULL, '', 57, NULL, ''),
(141, 'MD', 'Moldova, Republic of', '1', NULL, NULL, '', 56, NULL, ''),
(142, 'MC', 'Monaco', '1', NULL, NULL, '', 55, NULL, ''),
(143, 'MN', 'Mongolia', '1', NULL, NULL, '', 54, NULL, ''),
(144, 'MS', 'Montserrat', '1', NULL, NULL, '', 53, NULL, ''),
(145, 'MA', 'Morocco', '1', NULL, NULL, '', 52, NULL, ''),
(146, 'MZ', 'Mozambique', '1', NULL, NULL, '', 51, NULL, ''),
(147, 'MM', 'Myanmar', '1', NULL, NULL, '', 50, NULL, ''),
(148, 'NA', 'Namibia', '1', NULL, NULL, '', 49, NULL, ''),
(149, 'NR', 'Nauru', '1', NULL, NULL, '', 33, NULL, ''),
(150, 'NP', 'Nepal', '1', NULL, NULL, '', 32, NULL, ''),
(151, 'NL', 'Netherlands', '1', NULL, NULL, '', 31, NULL, ''),
(152, 'AN', 'Netherlands Antilles', '1', NULL, NULL, '', 15, NULL, ''),
(153, 'NC', 'New Caledonia', '1', NULL, NULL, '', 14, NULL, ''),
(154, 'NZ', 'New Zealand', '1', NULL, NULL, '', 13, NULL, ''),
(155, 'NI', 'Nicaragua', '1', NULL, NULL, '', 12, NULL, ''),
(156, 'NE', 'Niger', '1', NULL, NULL, '', 11, NULL, ''),
(157, 'NG', 'Nigeria', '1', NULL, NULL, '', 10, NULL, ''),
(158, 'NU', 'Niue', '1', NULL, NULL, '', 9, NULL, ''),
(159, 'NF', 'Norfork Island', '1', NULL, NULL, '', 8, NULL, ''),
(160, 'MP', 'Northern Mariana Islands', '1', NULL, NULL, '', 7, NULL, ''),
(161, 'NO', 'Norway', '1', NULL, NULL, '', 6, NULL, ''),
(162, 'OM', 'Oman', '1', NULL, NULL, '', 5, NULL, ''),
(163, 'PK', 'Pakistan', '1', '', '13', '', 4, NULL, ''),
(164, 'PW', 'Palau', '1', NULL, NULL, '', 16, NULL, ''),
(165, 'PA', 'Panama', '1', NULL, NULL, '', 17, NULL, ''),
(166, 'PG', 'Papua New Guinea', '1', NULL, NULL, '', 18, NULL, ''),
(167, 'PY', 'Paraguay', '1', NULL, NULL, '', 30, NULL, ''),
(168, 'PE', 'Peru', '1', NULL, NULL, '', 29, NULL, ''),
(169, 'PH', 'Philippines', '1', NULL, NULL, '', 28, NULL, ''),
(170, 'PN', 'Pitcairn', '1', NULL, NULL, '', 27, NULL, ''),
(171, 'PL', 'Poland', '1', NULL, NULL, '', 26, NULL, ''),
(172, 'PT', 'Portugal', '1', NULL, NULL, '', 25, NULL, ''),
(173, 'PR', 'Puerto Rico', '1', NULL, NULL, '', 24, NULL, ''),
(174, 'QA', 'Qatar', '1', NULL, NULL, '', 23, NULL, ''),
(175, 'RE', 'Reunion', '1', NULL, NULL, '', 22, NULL, ''),
(176, 'RO', 'Romania', '1', NULL, NULL, '', 21, NULL, ''),
(177, 'RU', 'Russian Federation', '1', NULL, NULL, '', 20, NULL, ''),
(178, 'RW', 'Rwanda', '1', NULL, NULL, '', 19, NULL, ''),
(179, 'KN', 'Saint Kitts and Nevis', '1', NULL, NULL, '', 2, NULL, ''),
(180, 'LC', 'Saint Lucia', '1', NULL, NULL, '', 62, NULL, ''),
(181, 'VC', 'Saint Vincent and the Grenadines', '1', NULL, NULL, '', 121, NULL, ''),
(182, 'WS', 'Samoa', '1', NULL, NULL, '', 105, NULL, ''),
(183, 'SM', 'San Marino', '1', NULL, NULL, '', 104, NULL, ''),
(184, 'ST', 'Sao Tome and Principe', '1', NULL, NULL, '', 103, NULL, ''),
(185, 'SA', 'Saudi Arabia', '1', NULL, NULL, '', 102, NULL, ''),
(186, 'SN', 'Senegal', '1', NULL, NULL, '', 101, NULL, ''),
(187, 'SC', 'Seychelles', '1', NULL, NULL, '', 100, NULL, ''),
(188, 'SL', 'Sierra Leone', '1', NULL, NULL, '', 99, NULL, ''),
(189, 'SG', 'Singapore', '1', NULL, NULL, '', 98, NULL, ''),
(190, 'SK', 'Slovakia', '1', NULL, NULL, '', 97, NULL, ''),
(191, 'SI', 'Slovenia', '1', NULL, NULL, '', 96, NULL, ''),
(192, 'SB', 'Solomon Islands', '1', NULL, NULL, '', 95, NULL, ''),
(193, 'SO', 'Somalia', '1', NULL, NULL, '', 94, NULL, ''),
(194, 'ZA', 'South Africa', '1', NULL, NULL, '', 106, NULL, ''),
(195, 'GS', 'South Georgia South Sandwich Islands', '1', NULL, NULL, '', 107, NULL, ''),
(196, 'ES', 'Spain', '1', NULL, NULL, '', 108, NULL, ''),
(197, 'LK', 'Sri Lanka', '1', NULL, NULL, '', 120, NULL, ''),
(198, 'SH', 'St. Helena', '1', NULL, NULL, '', 119, NULL, ''),
(199, 'PM', 'St. Pierre and Miquelon', '1', NULL, NULL, '', 118, NULL, ''),
(200, 'SD', 'Sudan', '1', NULL, NULL, '', 117, NULL, ''),
(201, 'SR', 'Suriname', '1', NULL, NULL, '', 116, NULL, ''),
(202, 'SJ', 'Svalbarn and Jan Mayen Islands', '1', NULL, NULL, '', 115, NULL, ''),
(203, 'SZ', 'Swaziland', '1', NULL, NULL, '', 114, NULL, ''),
(204, 'SE', 'Sweden', '1', NULL, NULL, '', 113, NULL, ''),
(205, 'CH', 'Switzerland', '1', NULL, NULL, '', 112, NULL, ''),
(206, 'SY', 'Syrian Arab Republic', '1', NULL, NULL, '', 111, NULL, ''),
(207, 'TW', 'Taiwan', '1', NULL, NULL, '', 110, NULL, ''),
(208, 'TJ', 'Tajikistan', '1', NULL, NULL, '', 109, NULL, ''),
(209, 'TZ', 'Tanzania, United Republic of', '1', NULL, NULL, '', 93, NULL, ''),
(210, 'TH', 'Thailand', '1', NULL, NULL, '', 92, NULL, ''),
(211, 'TG', 'Togo', '1', NULL, NULL, '', 91, NULL, ''),
(212, 'TK', 'Tokelau', '1', NULL, NULL, '', 75, NULL, ''),
(213, 'TO', 'Tonga', '1', NULL, NULL, '', 74, NULL, ''),
(214, 'TT', 'Trinidad and Tobago', '1', NULL, NULL, '', 73, NULL, ''),
(215, 'TN', 'Tunisia', '1', NULL, NULL, '', 72, NULL, ''),
(216, 'TR', 'Turkey', '1', NULL, NULL, '', 71, NULL, ''),
(217, 'TM', 'Turkmenistan', '1', NULL, NULL, '', 70, NULL, ''),
(218, 'TC', 'Turks and Caicos Islands', '1', NULL, NULL, '', 69, NULL, ''),
(219, 'TV', 'Tuvalu', '1', NULL, NULL, '', 68, NULL, ''),
(220, 'UG', 'Uganda', '1', NULL, NULL, '', 67, NULL, ''),
(221, 'UA', 'Ukraine', '1', NULL, NULL, '', 66, NULL, ''),
(222, 'AE', 'United Arab Emirates', '1', NULL, NULL, '', 65, NULL, ''),
(223, 'GB', 'United Kingdom', '1', NULL, NULL, '', 64, NULL, ''),
(224, 'UM', 'United States minor outlying islands', '1', NULL, NULL, '', 76, NULL, ''),
(225, 'UY', 'Uruguay', '1', NULL, NULL, '', 77, NULL, ''),
(226, 'UZ', 'Uzbekistan', '1', NULL, NULL, '', 78, NULL, ''),
(227, 'VU', 'Vanuatu', '1', NULL, NULL, '', 90, NULL, ''),
(228, 'VA', 'Vatican City State', '1', NULL, NULL, '', 89, NULL, ''),
(229, 'VE', 'Venezuela', '1', '', '14', '', 88, NULL, ''),
(230, 'VN', 'Vietnam', '1', '', NULL, '', 87, NULL, '84'),
(231, 'VG', 'Virigan Islands (British)', '1', NULL, NULL, '', 86, NULL, ''),
(232, 'VI', 'Virgin Islands (U.S.)', '1', NULL, NULL, '', 85, NULL, ''),
(233, 'WF', 'Wallis and Futuna Islands', '1', NULL, NULL, '', 84, NULL, ''),
(234, 'EH', 'Western Sahara', '1', NULL, NULL, '', 83, NULL, ''),
(235, 'YE', 'Yemen', '1', NULL, NULL, '', 82, NULL, ''),
(236, 'YU', 'Yugoslavia', '1', NULL, NULL, '', 81, NULL, ''),
(237, 'ZR', 'Zaire', '1', NULL, NULL, '', 80, NULL, ''),
(238, 'ZM', 'Zambia', '1', NULL, NULL, '', 79, NULL, ''),
(239, 'ZW', 'Zimbabwe', '1', NULL, NULL, '', 63, NULL, ''),
(240, 'CH', '中国', '1', '', NULL, '', 1, NULL, ''),
(241, 'US', 'United States of America', '1', '', NULL, '', -1, NULL, '');

-- --------------------------------------------------------



CREATE TABLE `documents` (
  `id` int(15) NOT NULL,
  `property_id` int(15) DEFAULT NULL,
  `title` varchar(500) DEFAULT NULL,
  `kind` varchar(200) DEFAULT NULL,
  `state` int(11) DEFAULT '1',
  `created_date` date DEFAULT NULL,
  `file_doc` text,
  `type` varchar(45) DEFAULT NULL,
  `description` text,
  `uploaded_by` int(11) DEFAULT NULL,
  `category` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `list_property_matches` (
  `id` int(11) NOT NULL,
  `title` varchar(500) DEFAULT NULL,
  `type` varchar(200) DEFAULT NULL,
  `number_res` int(11) DEFAULT NULL,
  `ids_match` varchar(500) DEFAULT NULL,
  `created_by` int(11) NOT NULL,
  `created_date` date DEFAULT NULL,
  `property_matches_id` int(11) DEFAULT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


CREATE TABLE `media` (
  `id` int(11) NOT NULL,
  `type` varchar(100) NOT NULL,
  `pro_id` int(11) NOT NULL,
  `title` varchar(250) NOT NULL,
  `path` varchar(250) NOT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '1',
  `featured` tinyint(4) NOT NULL,
  `description` text NOT NULL,
  `ordering` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- --------------------------------------------------------




CREATE TABLE `property` (
  `id` int(15) NOT NULL,
  `created_by` int(15) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  `kind_property` varchar(45) DEFAULT NULL,
  `type` varchar(45) DEFAULT NULL,
  `location` varchar(45) DEFAULT NULL,
  `caution` varchar(50) DEFAULT NULL,
  `status_mandate` varchar(200) DEFAULT NULL,
  `type_mandate` varchar(200) DEFAULT NULL,
  `startDate` varchar(500) DEFAULT NULL,
  `endDate` varchar(500) DEFAULT NULL,
  `certificate_date` varchar(100) DEFAULT NULL,
  `number_pay` varchar(15) DEFAULT NULL,
  `currency` varchar(45) DEFAULT NULL,
  `show_onssite` varchar(15) DEFAULT NULL,
  `number_charge` varchar(150) DEFAULT NULL,
  `type_charge` varchar(45) DEFAULT NULL,
  `auto_commission` tinyint(4) NOT NULL,
  `commission_seller` varchar(45) DEFAULT NULL,
  `fee_seller` varchar(45) DEFAULT NULL,
  `commission_buyer` varchar(45) DEFAULT NULL,
  `fee_buyer` varchar(150) DEFAULT NULL,
  `month_construction` varchar(45) DEFAULT NULL,
  `year_construction` varchar(45) DEFAULT NULL,
  `number_floors` varchar(150) DEFAULT NULL,
  `living_space` varchar(45) DEFAULT NULL,
  `number_floors_bulding` varchar(150) DEFAULT NULL,
  `total_area` varchar(50) DEFAULT NULL,
  `total_area_building` varchar(150) DEFAULT NULL,
  `park_inside` varchar(450) DEFAULT NULL,
  `park_outdoor` varchar(200) DEFAULT NULL,
  `outdoor_space` int(11) DEFAULT NULL,
  `energy_efficiency` varchar(200) DEFAULT NULL,
  `host_1` varchar(500) DEFAULT NULL,
  `host_2` varchar(500) DEFAULT NULL,
  `host_3` varchar(500) DEFAULT NULL,
  `file_des` text,
  `date_avai` varchar(100) DEFAULT NULL,
  `date_visit` varchar(100) DEFAULT NULL,
  `hour_visit_start` varchar(200) DEFAULT NULL,
  `hour_visit_end` varchar(200) DEFAULT NULL,
  `key_property` varchar(100) DEFAULT NULL,
  `keyword` varchar(1000) DEFAULT NULL,
  `number_floors_building` varchar(150) DEFAULT NULL,
  `orientation_terrace` varchar(200) DEFAULT NULL,
  `refreshments_topredict` varchar(500) DEFAULT NULL,
  `representation` varchar(200) DEFAULT NULL,
  `title_des` varchar(500) DEFAULT NULL,
  `total_commission_inclusive` varchar(500) DEFAULT NULL,
  `type_charges` varchar(500) DEFAULT NULL,
  `type_construction` varchar(500) DEFAULT NULL,
  `type_heating` varchar(400) DEFAULT NULL,
  `type_price` varchar(500) DEFAULT NULL,
  `type_property` varchar(200) DEFAULT NULL,
  `sub_type_property` varchar(500) DEFAULT NULL,
  `uploadDocument` varchar(11) DEFAULT NULL,
  `code` varchar(50) DEFAULT NULL,
  `key_avai` varchar(200) DEFAULT NULL,
  `des_pro` text,
  `more_des` varchar(500) DEFAULT NULL,
  `state` tinyint(4) DEFAULT '1',
  `title_project` text,
  `quantity_account_seen` int(11) DEFAULT '0',
  `cancel_reason` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;


CREATE TABLE `property_characteristic` (
  `id` int(11) NOT NULL,
  `property_id` int(11) NOT NULL,
  `number_room` varchar(50) DEFAULT NULL,
  `number_wc` varchar(50) DEFAULT NULL,
  `number_bathroom` varchar(50) DEFAULT NULL,
  `number_bedroom` varchar(50) DEFAULT NULL,
  `facilityDetails` text,
  `detail_rooms_values` text
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `property_location` (
  `id` int(11) NOT NULL,
  `property_id` int(15) NOT NULL,
  `street_name` varchar(45) DEFAULT NULL,
  `temperature` varchar(45) DEFAULT NULL,
  `app` varchar(45) DEFAULT NULL,
  `floor` int(15) DEFAULT NULL,
  `sector` varchar(45) DEFAULT NULL,
  `town` varchar(45) DEFAULT NULL,
  `area` varchar(45) DEFAULT NULL,
  `lat` varchar(45) DEFAULT NULL,
  `lng` varchar(45) DEFAULT NULL,
  `english` text,
  `french` text,
  `postal_code` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `property_marketing` (
  `id` int(11) NOT NULL,
  `property_id` int(15) NOT NULL,
  `at_home` varchar(45) DEFAULT NULL,
  `immotop` varchar(45) DEFAULT NULL,
  `wortimmo` varchar(45) DEFAULT NULL,
  `luxbazard` varchar(45) DEFAULT NULL,
  `immo_lu` varchar(45) DEFAULT NULL,
  `editus_lu` varchar(45) DEFAULT NULL,
  `editus_home` varchar(45) DEFAULT NULL,
  `luxembourg_wort` varchar(45) DEFAULT NULL,
  `distribution_flyers` varchar(45) DEFAULT NULL,
  `vitrine_agences` varchar(45) DEFAULT NULL,
  `autre_publicite` varchar(45) DEFAULT NULL,
  `facebook_personnel` varchar(200) DEFAULT NULL,
  `instagram` varchar(45) DEFAULT NULL,
  `linkedin` varchar(45) DEFAULT NULL,
  `sponsored_facebook_announcement` varchar(200) DEFAULT NULL,
  `agency_file` varchar(500) DEFAULT NULL,
  `urlYoutube` varchar(500) DEFAULT NULL,
  `agency_for_marketing` varchar(200) DEFAULT NULL,
  `at_home_input` varchar(45) DEFAULT NULL,
  `immotop_input` varchar(45) DEFAULT NULL,
  `wortimmo_input` varchar(45) DEFAULT NULL,
  `luxbazard_input` varchar(45) DEFAULT NULL,
  `immo_lu_input` varchar(45) DEFAULT NULL,
  `editus_lu_input` varchar(45) DEFAULT NULL,
  `editus_home_input` varchar(200) DEFAULT NULL,
  `luxembourg_wort_input` varchar(200) DEFAULT NULL,
  `distribution_flyers_input` varchar(200) DEFAULT NULL,
  `editus_home_agency` varchar(20) DEFAULT NULL,
  `luxembourg_wort_agency` varchar(20) DEFAULT NULL,
  `distribution_flyers_agency` varchar(20) DEFAULT NULL,
  `editus_lu_agency` varchar(20) DEFAULT NULL,
  `immo_lu_agency` varchar(20) DEFAULT NULL,
  `luxbazard_agency` varchar(20) DEFAULT NULL,
  `wortimmo_agency` varchar(20) DEFAULT NULL,
  `immotop_agency` varchar(20) DEFAULT NULL,
  `at_home_agency` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;




CREATE TABLE `property_match` (
  `id` int(11) NOT NULL,
  `title` varchar(1000) DEFAULT NULL,
  `kind_property` varchar(200) DEFAULT NULL,
  `send_contact` int(11) DEFAULT NULL,
  `sale` int(11) DEFAULT NULL,
  `rent` int(11) DEFAULT NULL,
  `date_avai` date DEFAULT NULL,
  `country` varchar(200) DEFAULT NULL,
  `criterias` varchar(5000) DEFAULT NULL,
  `price_min` float(50,2) DEFAULT NULL,
  `price_max` float(50,2) DEFAULT NULL,
  `type_property` text,
  `type_property_child` varchar(500) DEFAULT NULL,
  `type_construction` varchar(100) DEFAULT NULL,
  `cat_property` varchar(500) DEFAULT NULL,
  `bedrooms_min` int(11) DEFAULT NULL,
  `bedrooms_max` int(11) DEFAULT NULL,
  `rooms_min` int(11) DEFAULT NULL,
  `rooms_max` int(11) DEFAULT NULL,
  `bathrooms_min` int(11) DEFAULT NULL,
  `bathrooms_max` int(11) DEFAULT NULL,
  `separate_wc_min` int(11) DEFAULT NULL,
  `separate_wc_max` int(11) DEFAULT NULL,
  `living_space_min` int(11) DEFAULT NULL,
  `living_space_max` int(11) DEFAULT NULL,
  `floor_property_min` int(11) DEFAULT NULL,
  `floor_property_max` int(11) DEFAULT NULL,
  `area_min` int(11) DEFAULT NULL,
  `area_max` int(11) DEFAULT NULL,
  `outdoor_space` int(11) DEFAULT NULL,
  `more_infor` text,
  `search_type` varchar(100) DEFAULT NULL,
  `host_id` int(11) DEFAULT NULL,
  `host_name` varchar(45) DEFAULT NULL,
  `sector` varchar(45) DEFAULT NULL,
  `created_date` date DEFAULT NULL,
  `created_by` int(11) DEFAULT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `property_media` (
  `id` int(11) NOT NULL,
  `property_id` int(15) NOT NULL,
  `state` int(11) DEFAULT '1',
  `created_date` date DEFAULT NULL,
  `image` text,
  `title` varchar(500) DEFAULT NULL,
  `description` text,
  `primaryImage` varchar(45) DEFAULT NULL,
  `position` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;



CREATE TABLE `property_reorder` (
  `id` int(11) NOT NULL,
  `property_id` int(11) NOT NULL,
  `seller_id` int(11) DEFAULT NULL,
  `buyer_id` int(11) DEFAULT NULL,
  `collaborators_id` int(11) DEFAULT NULL,
  `contacts_id` varchar(200) DEFAULT NULL,
  `date_sale` varchar(100) DEFAULT NULL,
  `confirmed` int(11) NOT NULL DEFAULT '1',
  `date_entrance` varchar(100) DEFAULT NULL,
  `price` float(20,5) DEFAULT NULL,
  `seller_profit` varchar(2000) DEFAULT NULL,
  `buyer_profit` varchar(2000) DEFAULT NULL,
  `company_sell_id` int(11) NOT NULL,
  `collaborator_profit` int(11) DEFAULT NULL,
  `state` int(11) DEFAULT '1',
  `created_by` int(11) DEFAULT NULL,
  `created_date` varchar(100) DEFAULT NULL,
  `is_solo` int(11) DEFAULT '0',
  `property_price` float(20,5) DEFAULT NULL,
  `property_type` varchar(100) DEFAULT NULL,
  `seller_invoice` varchar(500) DEFAULT NULL,
  `buyer_invoice` varchar(500) DEFAULT NULL,
  `confirm_collaberate` varchar(45) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE `regions` (
  `id` int(11) NOT NULL,
  `type` varchar(500) NOT NULL,
  `parent_id` int(11) NOT NULL,
  `title` varchar(500) NOT NULL,
  `alias` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



INSERT INTO `regions` (`id`, `type`, `parent_id`, `title`, `alias`) VALUES
(1, '', 513, 'Bertrange', 'bertrange'),
(2, '', 514, 'Bissen', 'bissen'),
(3, '', 514, 'Roost', 'roost'),
(4, '', 515, 'Colmar-Berg', 'colmar-berg'),
(5, '', 515, 'Welsdorf', 'welsdorf'),
(6, '', 516, 'Contern', 'contern'),
(7, '', 516, 'Medingen', 'medingen'),
(8, '', 516, 'Moutfort', 'moutfort'),
(9, '', 516, 'Oetrange', 'oetrange'),
(10, '', 517, 'Angelsberg', 'angelsberg'),
(11, '', 517, 'Fischbach', 'fischbach'),
(12, '', 517, 'Koedange', 'koedange'),
(13, '', 517, 'Schiltzberg', 'schiltzberg'),
(14, '', 517, 'Schoos', 'schoos'),
(15, '', 518, 'Heffingen', 'heffingen'),
(16, '', 518, 'Reuland', 'reuland'),
(17, '', 519, 'Ansembourg', 'ansembourg'),
(18, '', 519, 'Bill', 'bill'),
(19, '', 519, 'Boevange-sur-Atert', 'boevange-sur-atert'),
(20, '', 519, 'Bour', 'bour'),
(21, '', 519, 'Brouch', 'brouch'),
(22, '', 519, 'Buschdorf', 'buschdorf'),
(23, '', 519, 'Finsterthal', 'finsterthal'),
(24, '', 519, 'Grevenknapp', 'grevenknapp'),
(25, '', 519, 'Hollenfels', 'hollenfels'),
(26, '', 519, 'Marienthal', 'marienthal'),
(27, '', 519, 'Openthalt', 'openthalt'),
(28, '', 519, 'Tuntange', 'tuntange'),
(29, '', 520, 'Alzingen', 'alzingen'),
(30, '', 520, 'Fentange', 'fentange'),
(31, '', 520, 'Hesperange', 'hesperange'),
(32, '', 520, 'Howald', 'howald'),
(33, '', 520, 'Itzig', 'itzig'),
(34, '', 521, 'Ernzen', 'ernzen'),
(35, '', 521, 'Larochette', 'larochette'),
(36, '', 521, 'Meysembourg', 'meysembourg'),
(37, '', 522, 'Gosseldange', 'gosseldange'),
(38, '', 522, 'Lintgen', 'lintgen'),
(39, '', 522, 'Prettingen', 'prettingen'),
(40, '', 523, 'Asselscheuer', 'asselscheuer'),
(41, '', 523, 'Blaschette', 'blaschette'),
(42, '', 523, 'Bofferdange', 'bofferdange'),
(43, '', 523, 'Helmdange', 'helmdange'),
(44, '', 523, 'Hunsdorf', 'hunsdorf'),
(45, '', 523, 'Lorentzweiler', 'lorentzweiler'),
(46, '', 524, 'Luxembourg', 'luxembourg'),
(47, '', 524, 'Beggen', 'beggen'),
(48, '', 524, 'Belair', 'belair'),
(49, '', 524, 'Bonnevoie', 'bonnevoie'),
(50, '', 524, 'Centre', 'centre'),
(51, '', 524, 'Cents', 'cents'),
(52, '', 524, 'Cessange', 'cessange'),
(53, '', 524, 'Clausen', 'clausen'),
(54, '', 524, 'Dommeldange', 'dommeldange'),
(55, '', 524, 'Eich', 'eich'),
(56, '', 524, 'Gare', 'gare'),
(57, '', 524, 'Gasperich', 'gasperich'),
(58, '', 524, 'Grund', 'grund'),
(59, '', 524, 'Hamm', 'hamm'),
(60, '', 524, 'Hollerich', 'hollerich'),
(61, '', 524, 'Kirchberg', 'kirchberg'),
(62, '', 524, 'Kohlenberg', 'kohlenberg'),
(63, '', 524, 'Limpertsberg', 'limpertsberg'),
(64, '', 524, 'Merl', 'merl'),
(65, '', 524, 'Muhlenbach', 'muhlenbach'),
(66, '', 524, 'Neudorf', 'neudorf'),
(67, '', 524, 'Pfaffenthal', 'pfaffenthal'),
(68, '', 524, 'Pulvermuehle', 'pulvermuehle'),
(69, '', 524, 'Reckenthal', 'reckenthal'),
(70, '', 524, 'Rollingergrund', 'rollingergrund'),
(71, '', 524, 'Verlorenkost', 'verlorenkost'),
(72, '', 524, 'Weimershof', 'weimershof'),
(73, '', 524, 'Weimerskirch', 'weimerskirch'),
(74, '', 525, 'Beringen', 'beringen'),
(75, '', 525, 'Berschbach', 'berschbach'),
(76, '', 525, 'Essingen', 'essingen'),
(77, '', 525, 'Mersch', 'mersch'),
(78, '', 525, 'Moesdorf', 'moesdorf'),
(79, '', 525, 'Pettingen', 'pettingen'),
(80, '', 525, 'Reckange', 'reckange'),
(81, '', 525, 'Rollingen', 'rollingen'),
(82, '', 525, 'Schoenfels', 'schoenfels'),
(83, '', 526, 'Ernster', 'ernster'),
(84, '', 526, 'Hostert', 'hostert'),
(85, '', 526, 'Niederanven', 'niederanven'),
(86, '', 526, 'Oberanven', 'oberanven'),
(87, '', 526, 'Rameldange', 'rameldange'),
(88, '', 526, 'Senningen', 'senningen'),
(89, '', 526, 'Senningerberg', 'senningerberg'),
(90, '', 527, 'Cruchten', 'cruchten'),
(91, '', 527, 'Niederglabach', 'niederglabach'),
(92, '', 527, 'Nommern', 'nommern'),
(93, '', 527, 'Oberglabach', 'oberglabach'),
(94, '', 527, 'Schrondweiler', 'schrondweiler'),
(95, '', 528, 'Findel', 'findel'),
(96, '', 528, 'Sandweiler', 'sandweiler'),
(97, '', 529, 'Münsbach', 'münsbach'),
(98, '', 529, 'Neuhaeusgen', 'neuhaeusgen'),
(99, '', 529, 'Schrassig', 'schrassig'),
(100, '', 529, 'Schuttrange', 'schuttrange'),
(101, '', 529, 'Uebersyren', 'uebersyren'),
(102, '', 530, 'Heisdorf', 'heisdorf'),
(103, '', 530, 'Müllendorf', 'mullendorf'),
(104, '', 530, 'Steinsel', 'steinsel'),
(105, '', 531, 'Strassen', 'strassen'),
(106, '', 532, 'Bereldange', 'bereldange'),
(107, '', 532, 'Helmsange', 'helmsange'),
(108, '', 532, 'Walferdange', 'walferdange'),
(109, '', 533, 'Hassel', 'hassel'),
(110, '', 533, 'Syren', 'syren'),
(111, '', 533, 'Weiler-la-Tour', 'weiler-la-tour'),
(112, '', 534, 'Beaufort', 'beaufort'),
(113, '', 524, 'Bigelbach', 'bigelbach'),
(114, '', 534, 'Dillingen', 'dillingen'),
(115, '', 534, 'Grundhof', 'grundhof'),
(116, '', 534, 'Savelborn', 'savelborn'),
(117, '', 535, 'Altrier', 'altrier'),
(118, '', 535, 'Bech', 'bech'),
(119, '', 535, 'Geyershof', 'geyershof'),
(120, '', 535, 'Graulinster', 'graulinster'),
(121, '', 535, 'Hemstal', 'hemstal'),
(122, '', 535, 'Hersberg', 'hersberg'),
(123, '', 535, 'Kobenbour', 'kobenbour'),
(124, '', 535, 'Rippig', 'rippig'),
(125, '', 535, 'Zittig', 'zittig'),
(126, '', 536, 'Berdorf', 'berdorf'),
(127, '', 536, 'Bollendorf-Pont', 'bollendorf-Pont'),
(128, '', 536, 'Weilerbach', 'weilerbach'),
(129, '', 537, 'Berg', 'berg'),
(130, '', 537, 'Betzdorf', 'betzdorf'),
(131, '', 537, 'Mensdorf', 'mensdorf'),
(132, '', 537, 'Olingen', 'olingen'),
(133, '', 537, 'Roodt-sur-syre', 'roodt-sur-syre'),
(134, '', 538, 'Biwer', 'biwer'),
(135, '', 538, 'Boudler', 'boudler'),
(136, '', 538, 'Boudlerbach', 'boudlerbach'),
(137, '', 538, 'Breinert', 'breinert'),
(138, '', 538, 'Brouch', 'brouch'),
(139, '', 538, 'Hagelsdorf', 'hagelsdorf'),
(140, '', 538, 'Wecker', 'wecker'),
(141, '', 538, 'Weydig', 'weydig'),
(142, '', 539, 'Assel', 'assel'),
(143, '', 539, 'Bous', 'bous'),
(144, '', 539, 'Erpeldange', 'erpeldange'),
(145, '', 539, 'Rolling', 'rolling'),
(146, '', 540, 'Breidweiler', 'breidweiler'),
(147, '', 540, 'Colbette', 'colbette'),
(148, '', 540, 'Consdorf', 'consdorf'),
(149, '', 540, 'Kalkesbach', 'kalkesbach'),
(150, '', 540, 'Marscherwald', 'marscherwald'),
(151, '', 540, 'Scheidgen', 'scheidgen'),
(152, '', 540, 'Wolper', 'wolper'),
(153, '', 541, 'Dalheim', 'dalheim'),
(154, '', 541, 'Filsdorf', 'filsdorf'),
(155, '', 541, 'Welfrange', 'welfrange'),
(156, '', 542, 'Echternach', 'echternach'),
(157, '', 543, 'Beyren', 'beyren'),
(158, '', 543, 'Flaxweiler', 'flaxweiler'),
(159, '', 543, 'Gostingen', 'gostingen'),
(160, '', 543, 'Niederdonven', 'niederdonven'),
(161, '', 543, 'Oberdonven', 'oberdonven'),
(162, '', 544, 'Grevenmacher', 'grevenmacher'),
(163, '', 545, 'Altinster ', 'altinster '),
(164, '', 545, 'Beidweiler', 'beidweiler'),
(165, '', 545, 'Blumenthal', 'blumenthal'),
(166, '', 545, 'Bourglinster ', 'bourglinster '),
(167, '', 545, 'Eisenborn', 'eisenborn'),
(168, '', 545, 'Eschweiler', 'eschweiler'),
(169, '', 545, 'Godbrange', 'godbrange'),
(170, '', 545, 'Gonderange', 'gonderange'),
(171, '', 545, 'Graulinster', 'graulinster'),
(172, '', 545, 'Imbringen', 'imbringen'),
(173, '', 545, 'Junglinster', 'junglinster'),
(174, '', 545, 'Rodenbourg', 'rodenbourg'),
(175, '', 545, 'Stuppicht', 'stuppicht'),
(176, '', 545, 'Weyer', 'weyer'),
(177, '', 546, 'Canach', 'canach'),
(178, '', 546, 'Lenningen', 'lenningen'),
(179, '', 547, 'Berbourg', 'berbourg'),
(180, '', 547, 'Leilig', 'leilig'),
(181, '', 547, 'Manternach', 'manternach'),
(182, '', 547, 'Muenschecker', 'muenschecker'),
(183, '', 548, 'Mertert', 'mertert'),
(184, '', 548, 'Wasserbillig', 'wasserbillig'),
(185, '', 549, 'Altwies', 'altwies'),
(186, '', 549, 'Ellange', 'ellange'),
(187, '', 549, 'Mondorf-les-Bains', 'mondorf-les-Bains'),
(188, '', 550, 'Remich', 'remich'),
(189, '', 551, 'Born', 'born'),
(190, '', 551, 'Boursdorf', 'boursdorf'),
(191, '', 551, 'Dickweiler', 'dickweiler'),
(192, '', 551, 'Girst', 'girst'),
(193, '', 551, 'Girstklaus', 'girstklaus'),
(194, '', 551, 'Herborn', 'herborn'),
(195, '', 551, 'Hinkel', 'hinkel'),
(196, '', 551, 'Lilien', 'lilien'),
(197, '', 551, 'Moersdorf', 'moersdorf'),
(198, '', 551, 'Mompach', 'mompach'),
(199, '', 551, 'Osweiler', 'osweiler'),
(200, '', 551, 'Rosport', 'rosport'),
(201, '', 551, 'Steinheim', 'steinheim'),
(202, '', 552, 'Bech-Kleinmacher', 'bech-kleinmacher'),
(203, '', 552, 'Burmerange', 'burmerange'),
(204, '', 552, 'Elvange', 'elvange'),
(205, '', 552, 'Emerange', 'emerange'),
(206, '', 552, 'Remerschen', 'remerschen'),
(207, '', 552, 'Schengen', 'schengen'),
(208, '', 552, 'Schwebsange', 'schwebsange'),
(209, '', 552, 'Schwebsingen', 'schwebsingen'),
(210, '', 552, 'Wellenstein', 'wellenstein'),
(211, '', 552, 'Wintrange', 'wintrange'),
(212, '', 553, 'Greiveldange', 'greiveldange'),
(213, '', 553, 'Hettermillen', 'hettermillen'),
(214, '', 553, 'Stadtbredimus', 'stadtbredimus'),
(215, '', 554, 'Christnach', 'christnach'),
(216, '', 554, 'Freckeisen', 'freckeisen'),
(217, '', 554, 'Haller', 'haller'),
(218, '', 554, 'Medernach', 'medernach'),
(219, '', 554, 'Mullerthal', 'mullerthal'),
(220, '', 554, 'Waldbillig', 'waldbillig'),
(221, '', 555, 'Ersange', 'ersange'),
(222, '', 555, 'Roedt', 'roedt'),
(223, '', 555, 'Trintange', 'trintange'),
(224, '', 555, 'Waldbredimus', 'waldbredimus'),
(225, '', 556, 'Ahn', 'ahn'),
(226, '', 556, 'Ehnen', 'ehnen'),
(227, '', 556, 'Kapenacker', 'kapenacker'),
(228, '', 556, 'Machtum', 'machtum'),
(229, '', 556, 'Wormeldange-Haut', 'wormeldange-Haut'),
(230, '', 557, 'Bettendorf', 'bettendorf'),
(231, '', 557, 'Gilsdorf', 'gilsdorf'),
(232, '', 557, 'Moestroff', 'moestroff'),
(233, '', 558, 'Baschleiden', 'baschleiden'),
(234, '', 558, 'Boulaide', 'boulaide'),
(235, '', 558, 'Surré', 'surré'),
(236, '', 559, 'Bourscheid', 'bourscheid'),
(237, '', 559, 'Ennerschlenner', 'ennerschlenner'),
(238, '', 559, 'Flebour', 'flebour'),
(239, '', 559, 'Friedbusch', 'friedbusch'),
(240, '', 559, 'Goebelsmuehle', 'goebelsmuehle'),
(241, '', 559, 'Kehmen', 'kehmen'),
(242, '', 559, 'Lipperscheid', 'lipperscheid'),
(243, '', 559, 'Michelau', 'michelau'),
(244, '', 559, 'Scheidel', 'scheidel'),
(245, '', 559, 'Schlindermanderscheid', 'schlindermanderscheid'),
(246, '', 559, 'Welscheid', 'welscheid'),
(247, '', 560, 'Diekirch', 'diekirch'),
(248, '', 561, 'Burden', 'burden'),
(249, '', 561, 'Ingeldorf', 'ingeldorf'),
(250, '', 562, 'Erpeldange-sur-Sûre', 'erpeldange-sur-sure'),
(251, '', 563, 'Dirbach', 'dirbach'),
(252, '', 563, 'Esch-sur-Sûre', 'esch-sur-sure'),
(253, '', 563, 'Eschdorf', 'eschdorf'),
(254, '', 563, 'Heiderscheid', 'heiderscheid'),
(255, '', 563, 'Heiderscheidergrund', 'heiderscheidergrund'),
(256, '', 563, 'Hierheck', 'hierheck'),
(257, '', 563, 'Insenborn', 'insenborn'),
(258, '', 563, 'Lultzhausen', 'lultzhausen'),
(259, '', 563, 'Merscheid', 'merscheid'),
(260, '', 563, 'Neunhausen', 'neunhausen'),
(261, '', 563, 'Ringel', 'ringel'),
(262, '', 563, 'Tadler', 'tadler'),
(263, '', 564, 'Ettelbrück', 'ettelbruck'),
(264, '', 564, 'Grentzingen', 'grentzingen'),
(265, '', 564, 'Warken', 'warken'),
(266, '', 565, 'Feulen', 'feulen'),
(267, '', 565, 'Niederfeulen', 'niederfeulen'),
(268, '', 565, 'Oberfeulen', 'oberfeulen'),
(269, '', 566, 'Bockholtz', 'bockholtz'),
(270, '', 566, 'Buederscheid ', 'buederscheid '),
(271, '', 566, 'Dahl', 'dahl'),
(272, '', 566, 'Goesdorf', 'goesdorf'),
(273, '', 566, 'Masseler', 'masseler'),
(274, '', 566, 'Nocher', 'nocher'),
(275, '', 566, 'Nocher-Route', 'nocher-route'),
(276, '', 567, 'Alscheid', 'alscheid'),
(277, '', 567, 'Enscherange', 'enscherange'),
(278, '', 567, 'Kautenbach', 'kautenbach'),
(279, '', 567, 'Lellingen', 'lellingen'),
(280, '', 567, 'Merkholtz', 'merkholtz'),
(281, '', 567, 'Pintsch', 'pintsch'),
(282, '', 567, 'Wilwerwiltz', 'wilwerwiltz'),
(283, '', 568, 'Bavigne', 'bavigne'),
(284, '', 568, 'Harlange', 'harlange'),
(285, '', 568, 'Kaundorf', 'kaundorf'),
(286, '', 568, 'Liefrange', 'liefrange'),
(287, '', 568, 'Mecher', 'mecher'),
(288, '', 568, 'Nothum', 'nothum'),
(289, '', 568, 'Tarchamps', 'tarchamps'),
(290, '', 568, 'Watrange', 'watrange'),
(291, '', 569, 'Mertzig', 'mertzig'),
(292, '', 570, 'Bockholtz', 'bockholtz'),
(293, '', 570, 'Brandenbourg', 'brandenbourg'),
(294, '', 570, 'Consthum', 'consthum'),
(295, '', 570, 'Dorscheid', 'dorscheid'),
(296, '', 570, 'Eisenbach', 'eisenbach'),
(297, '', 570, 'Flebour', 'flebour'),
(298, '', 570, 'Holzthum', 'holzthum'),
(299, '', 570, 'Hoscheid', 'hoscheid'),
(300, '', 570, 'Hoscheid-Dickt', 'hoscheid-Dickt'),
(301, '', 570, 'Hosingen', 'hosingen'),
(302, '', 570, 'Keppenhaff', 'keppenhaff'),
(303, '', 570, 'Neidhausen', 'neidhausen'),
(304, '', 570, 'Obereisenbach', 'obereisenbach'),
(305, '', 570, 'Roderschausen', 'roderschausen'),
(306, '', 570, 'Untereisenbach', 'untereisenbach'),
(307, '', 570, 'Wahlhausen', 'wahlhausen'),
(308, '', 571, 'Bivels', 'bivels'),
(309, '', 571, 'Gralingen', 'gralingen'),
(310, '', 571, 'Merscheid', 'merscheid'),
(311, '', 571, 'Nachtmanderscheid', 'nachtmanderscheid'),
(312, '', 571, 'Putscheid', 'putscheid'),
(313, '', 571, 'Stolzembourg', 'stolzembourg'),
(314, '', 571, 'Weiler', 'weiler'),
(315, '', 572, '=Hoesdorf', 'hoesdorf'),
(316, '', 572, 'Reisdorf', 'reisdorf'),
(317, '', 572, 'Wallendorf-Pont', 'wallendorf-Pont'),
(318, '', 573, 'Schieren', 'schieren'),
(319, '', 574, 'Bastendorf', 'bastendorf'),
(320, '', 574, 'Bettel', 'bettel'),
(321, '', 574, 'Brandenbourg', 'brandenbourg'),
(322, '', 574, 'Fouhren', 'fouhren'),
(323, '', 574, 'Landscheid', 'landscheid'),
(324, '', 574, 'Longsdorf', 'longsdorf'),
(325, '', 574, 'Selz', 'selz'),
(326, '', 574, 'Tandel', 'tandel'),
(327, '', 574, 'Walsdorf', 'walsdorf'),
(328, '', 575, 'Basbellain', 'basbellain'),
(329, '', 575, 'Biwisch', 'biwisch'),
(330, '', 575, 'Drinklange', 'drinklange'),
(331, '', 575, 'Goedange', 'goedange'),
(332, '', 575, 'Hautbellain', 'hautbellain'),
(333, '', 575, 'Huldange', 'huldange'),
(334, '', 575, 'Sassel', 'sassel'),
(335, '', 575, 'Troisvierges', 'troisvierges'),
(336, '', 575, 'Wilwerdange', 'wilwerdange'),
(337, '', 576, 'Eppeldorf', 'eppeldorf'),
(338, '', 576, 'Ermsdorf', 'ermsdorf'),
(339, '', 576, 'Folkendange', 'folkendange'),
(340, '', 576, 'Keiwelbach', 'keiwelbach'),
(341, '', 576, 'Medernach', 'medernach'),
(342, '', 576, 'Stegen', 'stegen'),
(343, '', 577, 'Vianden', 'vianden'),
(344, '', 578, 'Beiler', 'beiler'),
(345, '', 578, 'Binsfeld', 'binsfeld'),
(346, '', 578, 'Breidfeld', 'breidfeld'),
(347, '', 578, 'Holler', 'holler'),
(348, '', 578, 'Kaesfurt', 'kaesfurt'),
(349, '', 578, 'Leithum', 'leithum'),
(350, '', 578, 'Weiswampach', 'weiswampach'),
(351, '', 578, 'Wemperhardt', 'wemperhardt'),
(352, '', 579, 'Erpeldange', 'erpeldange'),
(353, '', 579, 'Eschweiler', 'eschweiler'),
(354, '', 579, 'Eschweiler-Wiltz', 'eschweiler-wiltz'),
(355, '', 579, 'Kleinhoscheid', 'kleinhoscheid'),
(356, '', 579, 'Knaphoscheid', 'knaphoscheid'),
(357, '', 579, 'Roullingen', 'roullingen'),
(358, '', 579, 'Selscheid', 'selscheid'),
(359, '', 579, 'Weidingen', 'weidingen'),
(360, '', 579, 'Wiltz', 'wiltz'),
(361, '', 580, 'Allerborn', 'allerborn'),
(362, '', 580, 'Asselborn', 'asselborn'),
(363, '', 580, 'Boevange', 'boevange'),
(364, '', 580, 'Boxhorn', 'boxhorn'),
(365, '', 580, 'Brachtenbach', 'brachtenbach'),
(366, '', 580, 'Cinqfontaines', 'cinqfontaines'),
(367, '', 580, 'Crendal', 'crendal'),
(368, '', 580, 'Deiffelt', 'deiffelt'),
(369, '', 580, 'Derenbach', 'derenbach'),
(370, '', 580, 'Doennange', 'doennange'),
(371, '', 580, 'Hachiville', 'hachiville'),
(372, '', 580, 'Hamiville', 'hamiville'),
(373, '', 580, 'Hoffelt', 'hoffelt'),
(374, '', 580, 'Lentzweiler', 'lentzweiler'),
(375, '', 580, 'Lullange', 'lullange'),
(376, '', 580, 'Maulusmuehle', 'maulusmuehle'),
(377, '', 580, 'Niederwampach', 'niederwampach'),
(378, '', 580, 'Oberwampach', 'oberwampach'),
(379, '', 580, 'Rumlange', 'rumlange'),
(380, '', 580, 'Schimpach', 'schimpach'),
(381, '', 580, 'Stockem', 'stockem'),
(382, '', 580, 'Troine', 'troine'),
(383, '', 580, 'Troine-Route', 'troine-route'),
(384, '', 580, 'Weiler', 'weiler'),
(385, '', 580, 'Wincrange', 'wincrange'),
(386, '', 581, 'Berlé', 'berlé'),
(387, '', 581, 'Doncols', 'doncols'),
(388, '', 581, 'Gruemmelscheid', 'gruemmelscheid'),
(389, '', 581, 'Noertrange', 'noertrange'),
(390, '', 581, 'Pommerloch', 'pommerloch'),
(391, '', 581, 'Schleif', 'schleif'),
(392, '', 581, 'Sonlez', 'sonlez'),
(393, '', 581, 'Winseler', 'winseler'),
(394, '', 582, 'Abweiler', 'abweiler'),
(395, '', 582, 'Bettembourg', 'bettembourg'),
(396, '', 582, 'Fennange', 'fennange'),
(397, '', 582, 'Huncherange', 'huncherange'),
(398, '', 582, 'Noertzange', 'noertzange'),
(399, '', 583, 'Differdange', 'differdange'),
(400, '', 583, 'Lasauvage', 'lasauvage'),
(401, '', 583, 'Niederkorn', 'niederkorn'),
(402, '', 583, 'Oberkorn', 'oberkorn'),
(403, '', 584, 'Dudelange', 'dudelange'),
(404, '', 585, 'Belval', 'belval'),
(405, '', 585, 'Esch-sur-Alzette', 'esch-sur-alzette'),
(406, '', 586, 'Aspelt', 'aspelt'),
(407, '', 586, 'Frisange', 'frisange'),
(408, '', 586, 'Hellange', 'hellange'),
(409, '', 587, 'Kayl', 'kayl'),
(410, '', 587, 'Tétange', 'tetange'),
(411, '', 588, 'Leudelange', 'leudelange'),
(412, '', 589, 'Bergem', 'bergem'),
(413, '', 589, 'Foetz', 'foetz'),
(414, '', 589, 'Mondercange', 'mondercange'),
(415, '', 589, 'Pontpierre', 'pontpierre'),
(416, '', 590, 'Lamadeleine', 'lamadeleine'),
(417, '', 590, 'Pétange', 'petange'),
(418, '', 590, 'Rodange', 'rodange'),
(419, '', 591, 'Ehlange', 'ehlange'),
(420, '', 591, 'Ehlange-sur-Mess', 'ehlange-sur-mess'),
(421, '', 591, 'Limpach', 'limpach'),
(422, '', 591, 'Pissange', 'pissange'),
(423, '', 591, 'Reckange-sur-Mess', 'reckange-sur-mess'),
(424, '', 591, 'Roedgen', 'roedgen'),
(425, '', 591, 'Wickrange', 'wickrange'),
(426, '', 592, 'Berchem', 'berchem'),
(427, '', 592, 'Bivange', 'bivange'),
(428, '', 592, 'Crauthem', 'crauthem'),
(429, '', 592, 'Kockelscheuer', 'kockelscheuer'),
(430, '', 592, 'Livange', 'livange'),
(431, '', 592, 'Peppange', 'peppange'),
(432, '', 592, 'Roeser', 'roeser'),
(433, '', 593, 'Rumelange', 'rumelange'),
(434, '', 594, 'Belvaux', 'belvaux'),
(435, '', 594, 'Ehlerange', 'ehlerange'),
(436, '', 594, 'Sanem', 'sanem'),
(437, '', 594, 'Soleuvre', 'soleuvre'),
(438, '', 595, 'Schifflange', 'schifflange'),
(439, '', 596, 'Beckerich', 'beckerich'),
(440, '', 596, 'Elvange', 'elvange'),
(441, '', 596, 'Hovelange', 'hovelange'),
(442, '', 596, 'Huttange', 'huttange'),
(443, '', 596, 'Levelange', 'levelange'),
(444, '', 596, 'Noerdange', 'noerdange'),
(445, '', 596, 'Oberpallen', 'oberpallen'),
(446, '', 596, 'Schweich', 'schweich'),
(447, '', 597, 'Bettange-sur-Mess', 'bettange-sur-mess'),
(448, '', 597, 'Dippach', 'dippach'),
(449, '', 597, 'Schouweiler', 'schouweiler'),
(450, '', 597, 'Sprinkange', 'sprinkange'),
(451, '', 598, 'Colpach-Bas', 'colpach-bas'),
(452, '', 598, 'Colpach-Haut', 'colpach-haut'),
(453, '', 598, 'Ell', 'ell'),
(454, '', 598, 'Petit-Nobressart', 'petit-nobressart'),
(455, '', 598, 'Roodt', 'roodt'),
(456, '', 599, 'Dahlem', 'dahlem'),
(457, '', 599, 'Garnich', 'garnich'),
(458, '', 599, 'Hivange', 'hivange'),
(459, '', 599, 'Kahler', 'kahler'),
(460, '', 600, 'Dellen', 'dellen'),
(461, '', 600, 'Ermsdorf', 'ermsdorf'),
(462, '', 600, 'Grosbous', 'grosbous'),
(463, '', 600, 'Lehrhof', 'lehrhof'),
(464, '', 602, 'Eischen', 'eischen'),
(465, '', 602, 'Gaichel', 'gaichel'),
(466, '', 602, 'Greisch', 'greisch'),
(467, '', 602, 'Hobscheid', 'hobscheid'),
(468, '', 602, 'Leesbach', 'leesbach'),
(469, '', 602, 'Roodt-sur-Eisch', 'roodt-sur-eisch'),
(470, '', 602, 'Septfontaines', 'septfontaines'),
(471, '', 602, 'Simmerfarn', 'simmerfarn'),
(472, '', 602, 'Simmerschmelz', 'simmerschmelz'),
(473, '', 603, 'Bascharage', 'bascharage'),
(474, '', 603, 'Clemency', 'clemency'),
(475, '', 603, 'Fingig', 'fingig'),
(476, '', 603, 'Hautcharage', 'hautcharage'),
(477, '', 603, 'Linger', 'linger'),
(478, '', 604, 'Kapweiler', 'kapweiler'),
(479, '', 605, 'Dondelange', 'dondelange'),
(480, '', 605, 'Kehlen', 'kehlen'),
(481, '', 605, 'Keispelt', 'keispelt'),
(482, '', 605, 'Meispelt', 'meispelt'),
(483, '', 605, 'Nospelt', 'nospelt'),
(484, '', 605, 'Olm', 'olm'),
(485, '', 606, 'Cap', 'cap'),
(486, '', 606, 'Goeblange', 'goeblange'),
(487, '', 606, 'Goetzingen', 'goetzingen'),
(488, '', 606, 'Koerich', 'koerich'),
(489, '', 606, 'Windhof', 'windhof'),
(490, '', 607, 'Bridel', 'bridel'),
(491, '', 607, 'Kopstal', 'kopstal'),
(492, '', 608, 'Cap', 'cap'),
(493, '', 608, 'Capellen', 'capellen'),
(494, '', 608, 'Holzem', 'holzem'),
(495, '', 608, 'Mamer', 'mamer'),
(496, '', 609, 'Bettborn', 'bettborn'),
(497, '', 609, 'Platen', 'platen'),
(498, '', 609, 'Pratz', 'pratz'),
(499, '', 609, 'Reimberg', 'reimberg'),
(500, '', 610, 'Arsdorf', 'arsdorf'),
(501, '', 610, 'Bigonville', 'bigonville'),
(502, '', 610, 'Bigonville-Poteau', 'bigonville-Poteau'),
(503, '', 610, 'Bilsdorf', 'bilsdorf'),
(504, '', 610, 'Eschette', 'eschette'),
(505, '', 610, 'Flatzbour', 'flatzbour'),
(506, '', 610, 'Folschette', 'folschette'),
(507, '', 610, 'Haut-Martelange', 'haut-martelange'),
(508, '', 610, 'Holtz', 'holtz'),
(509, '', 610, 'Hostert', 'hostert'),
(510, '', 610, 'Koetschette', 'koetschette'),
(511, '', 610, 'Perlé', 'perlé'),
(512, '', 610, 'Rambrouch', 'rambrouch'),
(513, '', 610, 'Riesenhof', 'riesenhof'),
(514, '', 610, 'Rombach-Martelange', 'rombach-martelange'),
(515, '', 610, 'Wolwelange', 'wolwelange'),
(516, '', 611, 'Eltz', 'eltz'),
(517, '', 611, 'Lannen', 'lannen'),
(518, '', 611, 'Nagem', 'nagem'),
(519, '', 611, 'Niederpallen', 'niederpallen'),
(520, '', 611, 'Ospern', 'ospern'),
(521, '', 611, 'Redange-sur-attert', 'redange-sur-attert'),
(522, '', 611, 'Reichlange', 'reichlange'),
(523, '', 612, 'Calmus', 'calmus'),
(524, '', 612, 'Ehner', 'ehner'),
(525, '', 612, 'Saeul', 'saeul'),
(526, '', 612, 'Schwebach', 'schwebach'),
(527, '', 613, 'Grass', 'grass'),
(528, '', 613, 'Hagen', 'hagen'),
(529, '', 613, 'Kleinbettinge', 'kleinbettinge'),
(530, '', 613, 'Steinfort', 'steinfort'),
(531, '', 614, 'Everlange', 'everlange'),
(532, '', 614, 'Rippweiler', 'rippweiler'),
(533, '', 614, 'Schandel', 'schandel'),
(534, '', 614, 'Useldange', 'useldange'),
(535, '', 615, 'Michelbouch', 'michelbouch'),
(536, '', 615, 'Vichten', 'vichten'),
(537, '', 616, 'Brattert', 'brattert'),
(538, '', 616, 'Buschrodt', 'buschrodt'),
(539, '', 616, 'Grevels', 'grevels'),
(540, '', 616, 'Heispelt', 'heispelt'),
(541, '', 616, 'Kuborn', 'kuborn'),
(542, '', 616, 'Rindschleiden', 'rindschleiden'),
(543, '', 616, 'Wahl', 'wahl');

-- --------------------------------------------------------



CREATE TABLE `subscribers` (
  `id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `sub_id` int(11) NOT NULL,
  `main_price` int(20) NOT NULL,
  `second_price` int(20) NOT NULL,
  `start_date` date NOT NULL,
  `end_date` date NOT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '1',
  `created_by` int(11) DEFAULT NULL,
  `created_date` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------



CREATE TABLE `subscriptions` (
  `id` int(11) NOT NULL,
  `title` varchar(1000) DEFAULT NULL,
  `main_price` int(20) DEFAULT NULL,
  `second_price` int(20) NOT NULL,
  `package_type` varchar(500) NOT NULL,
  `number_package` int(11) NOT NULL,
  `exact_number_days` int(11) NOT NULL,
  `state` tinyint(4) NOT NULL DEFAULT '1'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- --------------------------------------------------------



CREATE TABLE `typecontact` (
  `id` int(11) NOT NULL,
  `nametype` varchar(45) DEFAULT NULL,
  `account_id` varchar(45) DEFAULT NULL,
  `created` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;




ALTER TABLE `account`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `activity`
  ADD PRIMARY KEY (`id`),
  ADD KEY `user_id` (`pro_id`);


ALTER TABLE `agenda`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `category`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `city`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `contact`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `country`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `documents`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `list_property_matches`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `media`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property_characteristic`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property_location`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property_marketing`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property_match`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property_media`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `property_reorder`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `regions`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `subscribers`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `subscriptions`
  ADD PRIMARY KEY (`id`);


ALTER TABLE `typecontact`
  ADD PRIMARY KEY (`id`);

--

ALTER TABLE `account`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=272;


ALTER TABLE `activity`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `agenda`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

ALTER TABLE `category`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=338;


ALTER TABLE `city`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=617;


ALTER TABLE `contact`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=280;


ALTER TABLE `country`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=242;


ALTER TABLE `documents`
  MODIFY `id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=82;


ALTER TABLE `list_property_matches`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=454;


ALTER TABLE `media`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `property`
  MODIFY `id` int(15) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;


ALTER TABLE `property_characteristic`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;


ALTER TABLE `property_location`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;


ALTER TABLE `property_marketing`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=78;


ALTER TABLE `property_match`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=15;


ALTER TABLE `property_media`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=172;


ALTER TABLE `property_reorder`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=35;


ALTER TABLE `regions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=544;


ALTER TABLE `subscribers`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `subscriptions`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;


ALTER TABLE `typecontact`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT;
COMMIT;


